### ISSUE TITLE
Texture popup should use 3 columns on Windows

### ISSUE THREAD

**Issue by nt1m** [mozilla/FirefoxColor#102]
![screenshot-2018-2-27 firefox theme generator](https://user-images.githubusercontent.com/1795135/36758614-de62d252-1c0c-11e8-8b5b-a0036eefcb04.png)

I assume this is a bug due to the scrollbar.

**Comment by johngruen** [comment]
yeah i think, good catch!

Also we just got a fresh delivery of some hot new textures, so I'll add those this week too.

**Comment by lmorchard** [comment]
We're down to just one column in the texture selector now, so I think that basically addresses this issue

![capture](https://user-images.githubusercontent.com/21687/39013630-f215f2ec-43e5-11e8-9a9b-a6ee1ee52384.PNG)
