### ISSUE TITLE
Privacy and Terms links 404 on mozilla.github.io/ThemesRFun

### ISSUE THREAD

**Issue by pdehaan** [mozilla/FirefoxColor#103]
### Steps to repoduce:

1. Go to https://mozilla.github.io/ThemesRFun/
1. Click the "Privacy" or "Terms" links in the footer.

### Actual results:
Both links 404.

### Expected results:
No 404s.

https://github.com/mozilla/ThemesRFun/blob/5cdcb7e15d64934f0e71521512c74337dc58fa05/src/web/lib/components/AppFooter/index.js#L21-L26

This is probably because the dev site is hosted on GitHub Pages which uses the https://mozilla.github.io/ThemesRFun URL, where our repo is in a subfolder. Since the links are absolute (`<a href="/legal">...</a>`), they redirect you to https://mozilla.github.io/legal which doesn't work.

**Comment by lmorchard** [comment]
These pages don't actually exist yet - these are just placeholder links

**Comment by pdehaan** [comment]
But still, even if you create a /legal page, i think it'd still 404 since GitHub pages operates in a subdirectory of the mozilla.github.io domain. I think. But if OPs is hosting the stage/production pages on AWS, then QA could always verify there. Unless there is some other cheap solution, like setting the legal url to a relative URL like`./legal` instead of an absolute `/legal`.
