### ISSUE TITLE
Broken with Firefox v132

### ISSUE THREAD

**Issue by danielfleischer** [mozilla/FirefoxColor#1070]
No color theme is applied, everything is gray.

**Comment by Rob--W** [comment]
This is a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1928082

This will be fixed with the next release update, in 2 weeks.

As a work-around, select the chosen theme again at https://color.firefox.com

**Comment by danielfleischer** [comment]
Solved indeed with v132.0.1, thank you.
