### ISSUE TITLE
Letters, symbols and invalid values can wrongly be inserted in the color fields

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#120]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "ThemesRFun" add-on (0.0.24 custom build from 07.03.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "ThemesRFun" toolbar button.
3. Press the "Toolbar Color" button and select the values from the "A" field.
4. Insert any letters/symbols and observe the behavior.

**[Expected result]:**
- Nothing is displayed.

**[Actual result]:**
- The inserted letters/symbols are displayed.

**[Additional Notes]:
- The issue is reproducible with all the color pickers.
- The issue is also reproducible with the "R" "G" and "B" fields.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37094233-e20f8e22-221a-11e8-815c-30686504cd20.gif)

**Comment by lmorchard** [comment]
Do these invalid characters get saved? Looks like they revert back to something valid when you click away. I don't think we can restrict keystrokes inside the input fields of that component

**Comment by cedricium** [comment]
The invalid characters do not get saved and the input field value reverts back to last valid character sequence.
