### ISSUE TITLE
The "Firefox Theme Generator" tab's favicon does not change according to the selected color

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#121]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "ThemesRFun" add-on (0.0.24 custom build from 07.03.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "ThemesRFun" toolbar button.
3. Press the "Toolbar Color" button and select black.
4. Click the "Toolbar Icons and Text" and select a color visible on black (e.g. yellow).
5. Observe the "Firefox Theme Generator" tab's favicon

**[Expected result]:**
- The favicon color is changed to the chosen color.

**[Actual result]:**
- The favicon color remains black.

**[Additional Notes]:**
- This issue is reproducible with the default Firefox "Dark" theme enabled.
- The issue is not reproducible with the "about:addons" or with the "about:preferences" favicons.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37100125-dd95b29e-222a-11e8-9084-3c414ee095ab.gif)

**Comment by lmorchard** [comment]
The theme API does not affect website favicons, so the theme editor page icon is more like the "M" icon on the second tab. We *might* be able to hack something together to change the favicon, but it's not expected that it would change
