### ISSUE TITLE
The "Feedback" button wrongly redirects to an incomplete "Feedback" page

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#136]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button and press the "Feedback" button.
3. Observe the "Feedback" page.

**[Expected result]:**
- The "Feedback" page is displayed.

**[Actual result]:**
- Only the "Thank You" message is displayed and the survey is 100% completed.

**[Additional Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37159410-7fcb59b2-22f6-11e8-95c5-da70357c8def.gif)

**Comment by lmorchard** [comment]
This should be fixed before launch - I think we just don't have a complete survey available yet

**Comment by johngruen** [comment]
yeah, it's on my todo list, fine to track it here

**Comment by apoorvasingh17** [comment]
Can I work on this issue?

**Comment by lmorchard** [comment]
> Can I work on this issue?

@apoorvasingh17 Sorry, this one isn't really a good issue for contributors. We have to take care of building this survey internally at Mozilla

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Color" add-on (0.0.37 local-dev custom built on 22.05.2018) installed, on the latest Firefox release (60.0.1) and Nightly (62.0a1 Build ID - 20180521220045). 
Considering this I am closing this issue.

Verified on Windows 10 x64, Ubuntu 16.04 x64 and Mac 10.12.
