### ISSUE TITLE
The saved theme's "Delete" button is no longer highlighted after deleting a theme

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#137]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) installed from the "about:debugging" page.
- Have minimum two themes saved.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button and hover the first saved theme.
3. Click the "Delete" button and observe the behavior.

**[Expected result]:**
- The theme is deleted and the delete button of the following theme it is highlighted.

**[Actual result]:**
- The theme is deleted and the delete button is not highlighted.

**[Notes]:**
- If the mouse caret is moved then the button will be highlighted.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37159510-c716fd9e-22f6-11e8-8617-9a1ec1bd5438.gif)

**Comment by apoorvasingh17** [comment]
Can I work on this issue?

**Comment by lmorchard** [comment]
> Can I work on this issue?

Sure! Personally, I'm not sure how to fix this one. I think the delete highlight is just a CSS rule that seems to not apply when the elements on the page change. Maybe there's a transition or some hack we can do to make it work?
