### ISSUE TITLE
Integrate new GA ID string

### ISSUE THREAD

**Issue by wresuolc** [mozilla/FirefoxColor#142]
This is to replace the temporary string at https://github.com/mozilla/Themer/blob/master/package.json#L12 with a final string.  This depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1444225

**Comment by lmorchard** [comment]
One note to self (since I'll probably do this): Switch between the prod TID and the temporary dev TID based on whether the build is for prod or dev. That way, we don't get metrics pings sent from local dev to prod GA
