### ISSUE TITLE
"Uncaught (in promise) Metrics not sent due to DNT" error in Chrome

### ISSUE THREAD

**Issue by pdehaan** [mozilla/FirefoxColor#145]
Opened a theme URL locally in Chrome (64?), changed the "Theme Texture", and got the following in my DevTools console:

```
Uncaught (in promise) Metrics not sent due to DNT.                  index.js:175
```

![themer-chrome](https://user-images.githubusercontent.com/557895/37197659-70fecbbe-2330-11e8-9624-edb53d51fad5.png)

![firefox_themer_chromer](https://user-images.githubusercontent.com/557895/37197827-14f83822-2331-11e8-8190-436f7d923c2a.png)

Digging deeper, this may be coming from the [**testpilot-ga**](https://github.com/mozilla/testpilot-ga/blob/8f53d89b18d1d4745b3cff4251afd924802a596d/src/TestPilotGA.js#L101-L108) source... But not sure if we should be trying to catch upstream errors in our source or not.

---

**UPDATE:** Looks like the easiest/cheapest fix is to add a `.catch()` in: https://github.com/mozilla/Themer/blob/cf279fac5a7f1a81a937884a8569c61215585c42/src/lib/metrics.js#L77-L81

Something like:

```js
  sendEvent(...params) {
    if (analytics) {
      analytics.sendEvent(...params).catch(err => console.dir(err));
    }
  },
```

I'm not sure what's happening w/ the `err` response from [**testpilot-ga**'s `analytics.sendEvent()`](https://github.com/mozilla/testpilot-ga/blob/8f53d89b18d1d4745b3cff4251afd924802a596d/src/TestPilotGA.js#L107). It doesn't look/smell like an Error object, and feels more like a string...

**Comment by pdehaan** [comment]
Also, looking at this again in the morning... Should a version running locally via `npm run server` on localhost be sending metrics data?

**Comment by lmorchard** [comment]
> Should a version running locally via npm run server on localhost be sending metrics data?

Yeah, if only to verify that that part of the code works. But, once we have a real GA ID, [I'll probably stick some code in to switch to my "dev" TID rather than send data to the prod TID](https://github.com/mozilla/Themer/issues/142#issuecomment-371879735).

**Comment by wresuolc** [comment]
Test Pilot reserves cd19 for identifying the channel.  You're welcome to switch the ID, but just FYI:  https://github.com/mozilla/testpilot/blob/master/docs/experiments/ga.md#global-custom-dimensionsmetrics
