### ISSUE TITLE
Scale background images in BrowserPreview relative to the size of the component

### ISSUE THREAD

**Issue by johngruen** [mozilla/FirefoxColor#146]
This is probably stretch, but it would be nice to scale textures in the the BrowserPreview so that they accurately reflect how they'll look in the browser window. Since we need to tile them in CSS there are two ways i guess we get the dimensions we'd need to scale:

1. create an image tag for each bg we load, get the dimensions and pass them in to CSS
2.  add width and height into the file names somehow (bg-{height}-{width}-{id}) and just pull substrings out of the file name.

Not sure which is better, or maybe there's another way?

**Comment by johngruen** [comment]
FWIW, i think scaling on height is the important thing here so we could do something like backgroundSize: `${theme.images.bgHeight * dollScale.large} auto`

**Comment by caitmuenster** [comment]
This has been mentioned by two of our three theme power designers. Would be awesome if it could get on the roadmap for one of the upcoming releases.

**Comment by rebmullin** [comment]
hey @caitmuenster, I see a few places that I would consider "preview" so I wanted to verify that I am looking at the correct one. Can you please let me know if this is right:

![](https://monosnap.com/image/mC7VJT5Ovqi6apmdxxWNgAnbMIb4No.png)

**Comment by caitmuenster** [comment]
@rebmullin Yes, let's definitely start there! 

I'm not sure if the power users had any other feedback about this; I'm going to reach out and ask them. I'll add another comment when I've heard back from them.

**Comment by caitmuenster** [comment]
I didn't hear any additional feedback from the power theme users, so we can focus on scaling the image in the preview bar mentioned in the [comment above](https://github.com/mozilla/FirefoxColor/issues/146#issuecomment-549182370). :)

**Comment by rebmullin** [comment]
We got feedback from the community and this - #864 - was deployed to production on 4/13
