### ISSUE TITLE
Audit compliance to visual spec

### ISSUE THREAD

**Issue by youwenliang** [mozilla/FirefoxColor#15]
Assets: https://github.com/mozilla/testpilot-assets/tree/master/ThemesRFun/00_Assets
Measurements: https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/ThemesRFun/

Thanks!

**Comment by lmorchard** [comment]
From [acceptance criteria](https://github.com/mozilla/ThemesRFun/blob/master/docs/acceptance.md):

> - [ ] It should match final visual specs.

Another final checklist item for near the end

**Comment by lmorchard** [comment]
We've drifted quite a lot from the original visual spec. Good stuff, IMO, but probably invalidates this issue as a requirement
