### ISSUE TITLE
Dedupe saved themes?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/FirefoxColor#166]
### Steps to reproduce:
1. Go to https://mozilla.github.io/Themer/
2. Click the [Save] button on your theme a ~~few~~ dozen times.

### Actual results:
A few dozen duplicate themes in your "Saved themes" section.

### Expected results:
Maybe we should disallow people to save a theme if they have the same hash already saved in their saved themes.

**Comment by cedricium** [comment]
I came across the same issue and would agree, only having unique themes saved seems like a good idea. I wouldn't mind tackling this as part of my contribution for the Outreachy program.

I just wonder: if attempting to save a non-unique theme, should it fail silently or should there be some sort of notification / error? @lmorchard @johngruen

**Comment by johngruen** [comment]
Hey @cedricium I think you could just pop the theme the user is trying to dupe to the front of the saved themes list and then add a little highlight animation to it. probably fading in then out the same box shadow we show on hover would work well. If that's not strong enough we could think about adding a warning, but i bet that would do it.

**Comment by cedricium** [comment]
@johngruen great idea! Will see what I can do 👍

**Comment by Ekta3012** [comment]
Hello @pdehaan , i want to solve this issue as a part of outreachy programme. please, assign it to me.

**Comment by cedricium** [comment]
Hey @Ekta3012, I was working on this but was having trouble matching an already saved theme with the theme that is going to get saved. Definitely go ahead and give it shot, I'd love to see your solution.

**Comment by gargshruti30** [comment]
@cedricium can i work on this issue as a part of my Outreachy program ?
Please assign it to me I really want to work upon this issue.

**Comment by cedricium** [comment]
@gargshruti30 I'm an outreachy participant as well, not a member of the Themer group. Maybe go ahead and see if you can come up with a solution and think about making a PR afterwards.

**Comment by chuckharmston** [comment]
@gargshruti30 consider yourself assigned!

**Comment by chuckharmston** [comment]
@gargshruti30 consider yourself assigned!

**Comment by lmorchard** [comment]
> having trouble matching an already saved theme with the theme that is going to get saved.

For what it's worth, we have a small utility function here used for matching themes:

https://github.com/mozilla/Themer/blob/master/src/lib/store.js#L39

It's a hack and should be moved to `lib/themes.js` if it gets used outside `store.js`. But, it's what we use to compare an incoming shared theme with the current set theme to decide whether the "accept this shared theme" dialog should be shown

**Comment by pdehaan** [comment]
> For what it's worth, we have a small utility function here used for matching themes:

Fascinating! Is the order of `JSON.stringify()` guaranteed? I bit of quick ~~Googling~~ Yahoo!ing left me mildly confused.
https://github.com/auth0/node-jsonwebtoken/issues/404 points to https://github.com/nodejs/node/issues/15628, which seems to _imply_ that guaranteed ordering doesn't seem like it belongs in core (for Node.js, maybe each browser vendor's implementation can differ -- but I guess things may be the same if you're always using the same browser). But then it also points to substack's excellent looking [**json-stable-stringify**](https://github.com/substack/json-stable-stringify) module:

> **json-stable-stringify**: deterministic version of `JSON.stringify()` so you can get a consistent hash from stringified results.

**Comment by gargshruti30** [comment]
@lmorchard I will be sure to check that.

**Comment by csd713** [comment]
Raised a PR to avoid duplicating themes. #231 
Need help to hack the highlight animation effect suggested by @johngruen
