### ISSUE TITLE
The 'og:image' property should be explicitly provided

### ISSUE THREAD

**Issue by pdehaan** [mozilla/FirefoxColor#174]
### PREVIEW:

![og-preview](https://user-images.githubusercontent.com/557895/37416406-eca3bf52-276a-11e8-95e5-342a34b3f70f.png)

---

Via https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fmozilla.github.io%2FThemer%2F

![og-themer](https://user-images.githubusercontent.com/557895/37416301-aa9fe0f4-276a-11e8-925f-0e4dbc307147.png)

We'll also want to change that `og:url` once we're set up on some themer.firefox.com domain, or whatever.

**Comment by pdehaan** [comment]
And here's a dump of the current `<meta>` tags on https://mozilla.github.io/Themer/:

https://github.com/mozilla/Themer/blob/38933c93a6c304a70b095dfd737b3b2c8ce871d6/src/web/index.html.ejs#L6-L16

**Comment by Shruti9520** [comment]
@pdehaan Can I work on this? I probably left `og: image ` property. Can I correct this?

**Comment by pdehaan** [comment]
> I probably left `og:image` property. Can I correct this?

@johngruen Do you know if we have any assets for the `og:image` and `twitter:image`, and whatever else we may need for `<meta>` greatness?

I have to admit that I'm getting a bit lost in this. How do we share on Facebook/Twitter? Are we sharing Themer homepage? Should it share the URL of the _current theme_ you're staring at, because you wanted to promote the beautiful Hotdog Stand 🌭 theme with the world? If we're sharing the current theme page, I'm not sure if we could easily generate dynamic `og:image` images to give a nice photo preview (unless we can use some clever SVGs).

**Comment by pdehaan** [comment]
@Shruti9520 Let's wait on this for now until we can make sure we're using the correct/best UX assets for the preview image.

**Comment by Shruti9520** [comment]
@pdehaan Sure. :-)
I really appreciate the way you reply to other contributors :1st_place_medal: 

Thanks!

**Comment by lmorchard** [comment]
> How do we share on Facebook/Twitter? Are we sharing Themer homepage? Should it share the URL of the current theme you're staring at, because you wanted to promote the beautiful Hotdog Stand 🌭 theme with the world?

So far, just copy & paste the current URL or use the "Copy" button on the page. We'd talked about adding Twitter & Facebook share buttons, but @johngruen mentioned that those buttons actually don't seem to get used much in reality. 

Also... how to effectively enable & empower folks to share themes is one of the things we want to figure out with the experiment, so we don't have an answer up front 😁 

> If we're sharing the current theme page, I'm not sure if we could easily generate dynamic og:image images to give a nice photo preview (unless we can use some clever SVGs).

That's a good question and is one of the goals of issue #101 - my notion so far is that we could maybe fill in some color & background image properties in a templated SVG and then rasterize it with a microservice of some sort
