### ISSUE TITLE
Localize?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/FirefoxColor#182]
Per https://github.com/mozilla/Themer/pull/180#issuecomment-373746137

Not sure if we have l10n plans for v1 or what the timeline may be. But figured it's easier to submit a new issue where we can discuss and set a milestone/label versus me stupidly speculating in random GitHub issues.

---

Here's **mozilla/tab-split-2**'s localization ticket: https://github.com/mozilla/tab-split-2/issues/22

**Comment by lmorchard** [comment]
No, we don't have plans to localize for v1. Wanted to nail down the initial MVP before trying to get help from the l10n community
