### ISSUE TITLE
Change Save button text to Saved when it is clicked.

### ISSUE THREAD

**Issue by Shruti9520** [mozilla/FirefoxColor#184]
@lmorchard @pdehaan 
When I click on copy button it is changed from `copy` to `copied`. Which gave an excellent user experience. But when I click on `Save` button nothing happens. After clicking on save button, themes got saved down the page. So, for a new user, it takes some time to realize what is actually happening. I think it would be better if we change the save button text from `save` to `saved`, once it is clicked. 

Before clicking `Copy` button-
![themerissue1](https://user-images.githubusercontent.com/20228417/37608958-dd52076a-2bc1-11e8-9909-223df463c4b7.png)
After clicking `Copy` button-
![themerissue2](https://user-images.githubusercontent.com/20228417/37608997-fc3f09c0-2bc1-11e8-9921-187327f49b0d.png)

But in case of `Save` button-
Before clicking-
![themerissue3](https://user-images.githubusercontent.com/20228417/37609168-65ab2236-2bc2-11e8-8f6b-1b6f37fd39d3.png)

After clicking-
![themerissue4](https://user-images.githubusercontent.com/20228417/37609190-738c58d4-2bc2-11e8-8e4d-b258dd3068f1.png)

Thanks!

**Comment by johngruen** [comment]
@Shruti9520 sure, and maybe disable the button and maintain the 'saved' string until the theme gets changed?

**Comment by Shruti9520** [comment]
@johngruen Sounds great! :-)

**Comment by shr7** [comment]
Hi @Shruti9520, are you working on this issue?

**Comment by Shruti9520** [comment]
Hi, @shr7 
My approach to solve this issue is like this-
I will change the `Save` text to `Saved` and disable it. Afterward, check if URL is changed or not. So, the `Saved` string is mained until the URL is changed. 

What is yours? We can work on this together. :-)

**Comment by HandsomeMedia** [comment]
I took a stab at this tonight, since it appeared to have stalled.  Forgive me if I stepped on anyone's toes!
Also, forgive my React/Redux skills - I'm more comfortable in vanilla.  I'd love mentoring feedback on this PR, and I'm willing to refactor if need be!

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Color" add-on (0.0.35 custom built on 19.04.2018) installed on the latest Firefox Release and Nightly. Verified on Windows 10 x64, Arch Linux and Mac 10.13.
Now, after clicking the "Save" button, it changes into "Saved". But resolving this issue, caused this one: [246](https://github.com/mozilla/FirefoxColor/issues/246).
