### ISSUE TITLE
New name:  Firefox Color

### ISSUE THREAD

**Issue by wresuolc** [mozilla/FirefoxColor#203]
New approved name:  Firefox Color.  Please change anything as appropriate.  /cc @jbuck

**Comment by jbuck** [comment]
@wresuolc Does this also mean the production domain should be changed to color.firefox.com ?

**Comment by wresuolc** [comment]
@jbuck yes please. sorry for the trouble.  We discovered https://github.com/mjswensen/themer late in the game

**Comment by lmorchard** [comment]
This should be done now
