### ISSUE TITLE
Production monitoring

### ISSUE THREAD

**Issue by jbuck** [mozilla/FirefoxColor#207]
Need to setup the following bits of monitoring for production:

- [x] Pingdom check
- [x] Cloudfront metrics
- [x] Lambda function metrics

**Comment by wresuolc** [comment]
@jbuck ping on this too.  Is there an ETA or are you blocked on anything from us?  Thanks

**Comment by jbuck** [comment]
I've setup the Pingdom check for production, but I'd like to wait until we start seeing some production traffic before adding some more Cloudfront/Lambda metrics

**Comment by wresuolc** [comment]
kicking this out of MVP then

**Comment by jbuck** [comment]
This has been configured, there's a dashboard at https://app.datadoghq.com/dash/827808/firefox-color with http-level metrics
