### ISSUE TITLE
Clicking on Tab Highlight area on the preview panel wrongly opens the Toolbar Color Picker Panel

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#210]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the "Themer" add-on (0.0.33 stage build) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to: https://mozilla.github.io/Themer/
3. Click on "Tab Highlight Color" area on the preview panel. 

**[Expected result]:**
- "The Tab Highlight Color Picker" panel is open.

**[Actual result]:**
- "The Toolbar Color Picker" panel is open.

**[Notes]:**
- If you click on the "Tab Highlight Color" text bubble, it correctly opens the "Tab Highlight Color 
Picker" panel.
- Attached a screen recording of the issue:
![tab highlight color 3](https://user-images.githubusercontent.com/37875464/38078074-cacca4a4-3343-11e8-97ae-37de77bf812e.gif)

**Comment by johngruen** [comment]
Currently the tab-line is added as a border-top and not a separate element.

**Comment by johngruen** [comment]
This will be resolved if we close #211

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible with the latest version of the "FirefoxColor" add-on (0.0.35 custom built on 19.04.2018) installed on the latest Firefox release and Nightly. Now, clicking on browser preview elements no longer perform any action.
Verified on Windows 10 x64, Arch Linux and Mac 10.13.
