### ISSUE TITLE
Inconsistent behavior when trying to dismiss "Color Picker" panels from preview panel

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#211]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.33 custom build) 
installed from the "about:debugging" page..

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button.
3. Click on "Search Bar Color" area on the preview panel.
4. Click the same spot again.

**[Expected result]:**
- The "Search Bar Color" panel is closed.

**[Actual result]:**
- The "Search Bar Color" panel remains opened.

**[Notes]:**
- For "Toolbar Icons and Text" panel:
	If you click on the "Toolbar Icons and Text" area on the preview panel and click the same area again, the panel is dismissed.
	-attached a screen recording of the behavior:
![good behavior dismiss panel](https://user-images.githubusercontent.com/37875464/38092756-ccd83fc8-3371-11e8-91aa-30e18ff35705.gif)
	
- For "Toolbar color" and "Background color" panels:
	If you click on the "Toolbar color" or "Background color" area on the preview panel and click the same area again, the panel is not always dismissed (some areas work and some do not).
	-attached a screen recording of the issue:
![bad behavior dismiss panel only on some areas](https://user-images.githubusercontent.com/37875464/38092763-d232d53c-3371-11e8-80dd-b2966e5e5094.gif)

-For "Search Bar Color" and "Search Text" panels:
	If you click on the "Search Bar Color" or "Search Text" area on the preview panel and click the same area again, the panel is not dismissed.
	-attached a screen recording of the issue:
![bad behavior no dismiss](https://user-images.githubusercontent.com/37875464/38092772-d62e9a90-3371-11e8-9a3b-ac1625472ef8.gif)

**Comment by johngruen** [comment]
I don't have a strong opinion about this...maybe we should just disable clicks on the browser preview for now?

**Comment by johngruen** [comment]
Based on user testing i think we can/should disable this feature

**Comment by lmorchard** [comment]
> Based on user testing i think we can/should disable this feature

By "this feature" do you mean dismissing the panel? Or selecting properties by clicking on the browser preview altogether?

**Comment by johngruen** [comment]
Yeah, sorry...the ability to click on the browser preview itself.

**Comment by meandavejustice** [comment]
Hitting the `esc` key dismisses the panels, personally I would prioritize this as `post-mvp`. That's just my 2 cents :)

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible with the latest version of the "FirefoxColor" add-on (0.0.35 custom built on 19.04.2018) installed on the latest Firefox release and Nightly. Now, clicking on browser preview elements no longer perform any action.
Verified on Windows 10 x64, Arch Linux and Mac 10.13.
