### ISSUE TITLE
Clicking the "Firefox Color" toolbar button multiple times wrongly opens multiple tabs

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#223]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.35 custom build) 
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button multiple times (at least 5) in quick succession.
3. Observe the browser's behaviour.

**[Expected result]:**
- Only one tab with "Firefox Color" is opened. 

**[Actual result]:**
- Multiple tabs with "Firefox Color" are opened. 

**[Notes]:**
- This issue is easily reproducible when you start the browser or after leaving it for a while if a tab with "Firefox" color does not exist.
- Attached a screen recording of the issue:
![multiple tabs of firefoxcolor](https://user-images.githubusercontent.com/37875464/38681230-e6db4168-3e70-11e8-9394-aac4f7edd904.gif)

**Comment by csd713** [comment]
Hi @meandavejustice can I work on this issue?

**Comment by lmorchard** [comment]
Hmm, weird thing is that this [should already be implemented](https://github.com/mozilla/FirefoxColor/commit/b84dd4f836f7883b4ff49dc0859bd9b0dcbe2b0c) here:

https://github.com/mozilla/FirefoxColor/blob/master/src/extension/background.js#L18

But, it looks like we had a regression - possibly as part of renaming the project? 

I think the task for this issue will be troubleshooting that code and figuring out why it's not detecting an existing tab.

**Comment by cedricium** [comment]
I was the one who implemented #160 (check to see if FxColor tab exists before creating a new one) - just tried reproducing w/ FxColor v0.0.35 and could not. Is anyone else able to repro?

**Comment by csd713** [comment]
Even I'm unable to reproduce this issue with latest load (v "0.0.35" and Fx-59.0.2). Looks like it is fixed.

**Comment by cedricium** [comment]
Hey @Softvision-AndreeaCupsa, here are the steps I took to try and reproduce this issue:

1. `git clone` and `cd FirefoxColor/`.
2. `npm install`
3. `npm start`
4. In Firefox, navigate to `about:debugging` and select "Load Temporary Add-on", then chose the `manifest.json` file found in `FirefoxColor/build/extension/`.
5. Click the toolbar button (with and without the Firefox Color tab open).

Does that sound about right in terms of reproducing the issue?

**Comment by meandavejustice** [comment]
In our triage this morning @johngruen tried to reproduce this, looks like it is fixed. Closing

**Comment by lmorchard** [comment]
I can reproduce with these steps:
1. Start with no Firefox Color tabs open.
1. Click the toolbar button - new tab is created
1. Click the toolbar button again quickly, before the previous tab has finished loading - new tab is created

I think the problem is that we cannot detect an existing tab with the Firefox Color site until the tab has finished loading. We could maybe fix by having the add-on track when the button is clicked, then set a flag to ignore subsequent clicks until it can verify that the tab has been opened?

**Comment by johngruen** [comment]
Seems like not a good first issue

**Comment by rebmullin** [comment]
I could not replicate this issue. Please reopen again if you can replicate.
