### ISSUE TITLE
The "Undo" button is wrongly active even if nothing is changed when visiting the Firefox Color page for the first time

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#224]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Color" add-on (0.0.35 custom built on 12.04.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button and observe the "Undo" button.

**[Expected result]:**
- The "Undo" button is inactive.

**[Actual result]:**
- The "Undo" button is active and clickable.

**[Notes]:**
- If the "Undo" button is clicked, the "Redo" button becomes active.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38683938-3af0446e-3e77-11e8-9548-86e190958ba1.gif)

**Comment by Softvision-MariusComan** [comment]
After further investigation, I've found out that the actual behavior is a bit different. Each time a "Firefox Color" tab is opened the default theme is loaded and displayed for a brief amount of time. Only after that, it is changed to the previously selected theme.
This behavior causes the "Undo" button to activate even if no changes were being made. This affects also the browser's "Back" button that becomes also active.
Attached a new screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40055805-dd76e226-5851-11e8-830a-9f33fe77cd21.gif)

**Comment by lmorchard** [comment]
Does this issue still occur? I'm having trouble reproducing it myself

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible on Mac 10.13, Windows 10 x64 and Arch Linux on latest Nightly (64.0a1) with latest "Firefox Color" (1.1.0 dev version/ 12/09/2018) installed.
Now the "Undo" and "Redo" buttons are displayed only after a change is made to the set theme, or another theme is set.
Considering this I am closing this issue.

**Comment by lmorchard** [comment]
Thank you for verifying!
