### ISSUE TITLE
The theme textures are not highlighted when hovered

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#225]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (0.0.35 custom built on 12.04.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the Firefox Color toolbar button.
2. Click the "Theme Texture" bubble and hover any texture.
3. Observe the behavior.

**[Expected result]:**
- The themes textures are highlighted when hovered.

**[Actual result]:**
- Nothing happens.

**[Additional Notes]:**
- The preset themes are highlighted with blue borders when are hovered.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38684236-eb9eb034-3e77-11e8-8ce6-69da3b776ab9.gif)

**Comment by meandavejustice** [comment]
fixed in #232
