### ISSUE TITLE
The color is wrongly changed right after it is selected regardless of the selection method

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#226]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (0.0.35 custom built on 12.04.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the Firefox Color toolbar button.
2. Click on any bubble.
3. Select any preset color from the color picker and observe the values from the text fields while doing this.

**[Expected result]:**
- The values are displayed according to the selected color.

**[Actual result]:**
- The correct values are displayed but are changed right after that.

**[Additional Notes]:**
- This issue is also reproducible if the color is selected from the color field, by changing the values from the text fields or by moving the slider position.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38684699-eedc2212-3e78-11e8-8318-97c10aaf9dc1.gif)

**Comment by lmorchard** [comment]
I *think* this has been fixed here:
https://github.com/mozilla/FirefoxColor/pull/238

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Color" add-on (0.0.35 custom built on 23.04.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Ubuntu 14.04 x64 and Mac 10.12.
