### ISSUE TITLE
[Enhancement] The text from the "Copy" button should change back to "Copy" a few seconds after it has been clicked on

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#228]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.35 custom build) 
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Click on "Copy" button.
4. Wait a few seconds and observe the button's behaviour.

**[Expected result]:**
- The button's text changes back to "Copy".

**[Actual result]:**
- The button's text remains "Copied".

**[Notes]:**
- We have done similar effect on the "Send" experiment with the "Copy to clipboard" button. The button turns green and the text from it changes to a checkmark informing the user that the action has been completed after a few seconds changes back to blue and the text changes back to "Copy to clipboard".
- Attached a screen recording of the issue:
![copy text](https://user-images.githubusercontent.com/37875464/38685628-06b68218-3e7b-11e8-92b5-1c686e0e325c.gif)

**Comment by lmorchard** [comment]
It currently changes back to "Copy" when the theme is changed - and thus the URL is different. I don't think we need to set up a timer to force the button to change
