### ISSUE TITLE
Textures do not work in latest nightly

### ISSUE THREAD

**Issue by johngruen** [mozilla/FirefoxColor#230]
In 61.0a1 (2018-04-13) i get a console error when creating a theme with a background and no texture appears in  browser chrome

```
undefined index.js:21:4
uncaught exception: Request error: 0
```

**Comment by chuckharmston** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1454016

**Comment by meandavejustice** [comment]
Should be working again now https://bugzilla.mozilla.org/show_bug.cgi?id=1454016#c7
