### ISSUE TITLE
Theme Texture highlight effects appear cut off

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/FirefoxColor#236]
[Affected versions]:
- Firefox 59.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (0.0.35 custom built on 18.04.2018) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and click the Firefox Color toolbar button.
2. Click the "Theme Texture" bubble.
3. Hover the first item and observe it's highlight effect.

[Expected result]:
- The effect is fully visible.

[Actual result]:
- The effect appears cut off at the left, top and right margins.

[Notes]:
- The issue is also reproducible for the 2nd and 2nd to last items, but for them only the left and right margins appear this way.
- The issue is also reproducible for the last item, but for it the left, bottom and right margins appear cut.
- Attached a screen recording of the issue:
![theme texture highlight appears cut off](https://user-images.githubusercontent.com/18304511/38937719-8006ca46-432c-11e8-9015-093b3edb55a8.gif)

**Comment by HandsomeMedia** [comment]
I'll take a stab at it - I have the build loaded now and can replicate.

**Comment by HandsomeMedia** [comment]
I've got a simple fix ready.  Just reading up on how to push my changes.

**Comment by HandsomeMedia** [comment]
PR opened - apologies for the multiple commits on such a simple fix.  I made the first commit without reading contribution guidelines: 
https://github.com/mozilla/FirefoxColor/blob/master/CONTRIBUTING.md
😊

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible with the latest version of the "FirefoxColor" add-on (0.0.35 custom built on 19.04.2018) installed on the latest Firefox release and Nightly. The highlight effect is now fully visible and properly displayed on all items from "Theme Texture" bubble.
Verified on Windows 10 x64, Arch Linux and Mac 10.13.
