### ISSUE TITLE
The "Feedback" button is not expanded when focused using the keyboard

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/FirefoxColor#237]
[Affected versions]:
- Firefox 59.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (0.0.35 custom built on 18.04.2018) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and click the Firefox Color toolbar button.
2. Click somewhere in the "Firefox Color" string.
3. Press the "Tab" key twice and observe the behavior.

[Expected result]:
- The button expands.

[Actual result]:
- The button is focused but it does not expand.

[Notes]:
- Attached a screen recording of the issue:
![feedback button is not expanded when focused via keyboard](https://user-images.githubusercontent.com/18304511/38939345-680ba688-4330-11e8-8043-9af139cc74b3.gif)

**Comment by dominictwlee** [comment]
Hi, I'm a newbie contributor to open source but I could give this a go if no one else is working on it.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified that the issue is no longer reproducible on Mac 10.13.3, Win10 x64 and Arch Linux on latest Firefox (59.0.3) and latest Nightly (62.0a1) with Firefox Color (0.0.36) installed.
The "Feedback" button is expanded when focused using the keyboard.
