### ISSUE TITLE
Clicking inside the "Theme Texture" panel wrongly dismisses it

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#244]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**

- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.35 custom build)
installed from the "about:debugging" page..

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "FirefoxColor" toolbar button.
3. Click the "Theme Texture" bubble.
4. Click inside the "Theme Texture" panel.
5. Observe the behavior. 

**[Expected result]:**
Nothing changes.

**[Actual result]:**
Panel is dismissed. 

**[Notes]:**
- If you click inside other color picker panels, they don't get dismissed. 
- Attached a screen recording of the issue:
![click dismiss](https://user-images.githubusercontent.com/37875464/38999026-891da26c-43f9-11e8-9b55-49fa64ebfcef.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is still reproducible on Mac 10.13 and Windows 10 x64 on latest Firefox (60.0.1) and latest Nightly (62.0a1) with latest "Firefox Color" (1.0.0 04/06/2018) installed. 

The "Theme Texture" panel is wrongly dismissed if you click the white space between the theme textures, but is no longer dismissed if you click the panel margins.

Considering this I will reopen this issue.

**Comment by mgillespy** [comment]
@caitmuenster , can this be closed? It doesn't seem to be an issue anymore - the "theme texture" bubble has been removed, and user options display in a side panel rather than a popup.

**Comment by caitmuenster** [comment]
Yep, go ahead and close it, @mgillespy!

**Comment by rebmullin** [comment]
the ui has changed here so seems like this can be changed. please reopen with updates if needed. thanks!
