### ISSUE TITLE
Refreshing the page wrongly changes the "Saved" button into "Save"

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#246]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**

- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.35 custom build)
installed from the "about:debugging" page..

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Make any change in the theme.
4. Click the "Save" button.
5. Refresh the page and observe the "Saved" button.

**[Expected result]:**
- The button remains unchanged.

**[Actual result]:**
- "Saved" button is now "Save" and it is still inactive.

**[Notes]:**
- Attached a screen recording of the issue:
![save button](https://user-images.githubusercontent.com/37875464/39047947-78855e1c-44a4-11e8-8c53-bb32e5a0fea7.gif)

**Comment by lmorchard** [comment]
Refreshing the page loses the state of what was last saved, since you're starting a brand new session with the app. I guess we could compare the current theme against *all* saved themes every time, but I'm not sure we want that expense. We might just leave this one as an edge case.
