### ISSUE TITLE
Mouse pointer does not change into text selection pointer when hovering "Share your theme" text

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#249]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**

- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.35 custom build) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Go to "Share your theme" section and hover "Share your theme" text.
4. Observe the behavior of the mouse pointer.

**[Expected result]:**
- Mouse changes into a text select pointer.

**[Actual result]:**
- The arrow mouse pointer is still displayed.

**[Notes]:**
- Hovering over "Save your theme", "Choose a preset theme" and "Saved themes" changes the mouse into a text select pointer.
- Attached a screen recording of the issue:
![hover over share your theme](https://user-images.githubusercontent.com/37875464/39137531-82a298a4-4726-11e8-8d9b-56ede07cdb36.gif)

**Comment by ritikavnair** [comment]
Hi can I please take up this issue? I am a newbie to open source contributions and want to get started. Thanks.

**Comment by lmorchard** [comment]
Sure, give it a go!

**Comment by ritikavnair** [comment]
Hi, I have fixed the mentioned issue. Also, the same issue was happening when you hover over the text below the heading 'Share your theme', i.e: 'Copy and paste this URL to share your creation.' I have fixed that as well. I have put in the Pull Request. This is my first code contribution to an open source project. I hope I have performed the fix as expected and without glitches! Thank you!
