### ISSUE TITLE
CORS issues with adblockers

### ISSUE THREAD

**Issue by johngruen** [mozilla/FirefoxColor#256]
I sort of don't think this is an issue save for the uncaught exception, but will log it for discussion.
Noticed with uBlock Origin and DDG Privacy Essentials add-on. Metrics pings to GA trigger a CORS warning and a console error, namely:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.google-analytics.com/collect. (Reason: CORS request did not succeed).

uncaught exception: Request error: 0
```

**Comment by johngruen** [comment]
This is probably as expected... @lmorchard will take a peek

**Comment by johngruen** [comment]
We should catch the exception

**Comment by Rob--W** [comment]
GA was removed in https://github.com/mozilla/FirefoxColor/pull/784
