### ISSUE TITLE
cd2 is not working as described

### ISSUE THREAD

**Issue by johngruen** [mozilla/FirefoxColor#257]
`cd2` captures if a user begins a visit to the site from the browserAction, but it doesn't seem to be firing...

STR
1. Open the site from the browserAction
2. Pick a new preset theme
3. In the console, look at the metrics log object...`cd2` is set to `false`

expected: `cd2` is set to `true`

**Comment by lmorchard** [comment]
Looks like I added [a function to set the flag](https://github.com/mozilla/FirefoxColor/blob/cc5aec23a04f2b2bb76f8eae359fd71d26b01ed0/src/lib/metrics.js#L112), but never set things up to detect an add-on click. 

Could probably just add a query parameter to [the URL used to open a new tab from the toolbar button](https://github.com/mozilla/FirefoxColor/blob/cc5aec23a04f2b2bb76f8eae359fd71d26b01ed0/src/extension/background.js#L24) and then look for that parameter [in the web app start-up](https://github.com/mozilla/FirefoxColor/blob/cc5aec23a04f2b2bb76f8eae359fd71d26b01ed0/src/web/index.js#L209) to call `Metrics.setWasAddonClick(true)`
