### ISSUE TITLE
Clicking inside the "Privacy and Terms" pop-up wrongly dismisses it

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#264]
**[Affected versions]:**
- Firefox 59.0.3 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**

- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.35 custom build) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Go to footer section and click on "Privacy" or "Terms" button.
4. Click inside the pop-up.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The pop-up is dismissed.

**[Notes]:**
- Attached a screen recording of the issue:
![firefoxcolor pop up dismiss](https://user-images.githubusercontent.com/37875464/39629410-c6be6ea0-4fb4-11e8-857a-9e2f2dfa205c.gif)

**Comment by is2ei** [comment]
Hi @Softvision-AndreeaCupsa 
Could I work on this issue?

**Comment by pdehaan** [comment]
@is2ei Absolutely! Let us know if you have any questions.

**Comment by aniketkudale** [comment]
Looks like this is inactive for a while, I would like to work on this issue.

**Comment by is2ei** [comment]
@aniketkudale 
I'm afraid but I'm busy recently. Please take it if you want.

**Comment by aniketkudale** [comment]
Thanks @is2ei

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified that the issue is no longer reproducible on Mac 10.13.3, Windows 10 x64 and Arch Linux on latest Firefox (61.0.1) and latest Nightly (63.0a1) with latest "Firefox Color"(07/25/2018) version 1.0.1 custom build.

**Comment by aniketkudale** [comment]
Thanks for the comfirmation @Softvision-AndreeaCupsa :)
