### ISSUE TITLE
[Enhancement] The "Privacy and Terms" pop-up should be dismissed when pressing Esc key

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#266]
**[Affected versions]:**
- Firefox 59.0.3 and up

*[Affected Platforms]:*
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**

- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.35 custom build) installed from the "about:debugging" page.

*[Steps to reproduce]:*
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Go to footer section and click on "Privacy" or "Terms" button.
4. Press Esc key.

**[Expected result]:**
- The pop-up is dismissed. 

**[Actual result]:**
- The pop-up remains open.

**Comment by Vishal19111999** [comment]
Can I solve this as my first issue?

**Comment by Vishal19111999** [comment]
@caitmuenster Can I solve it as my first issue?

**Comment by Rob--W** [comment]
Hi @Vishal19111999 Sure. To resolve this issue, you could register a `"keydown"` event listener on the `document` in the dialog's `componentDidMount` (and unregister it from `componentWillUnmount`), which closes the dialog when the Esc key is hit.

Let me know if you have more questions.

**Comment by Vishal19111999** [comment]
I am facing some errors while installing npm packages...please help @Rob--W 
![Screenshot from 2019-09-24 13-43-21](https://user-images.githubusercontent.com/29145212/65494049-b9e78600-ded1-11e9-9416-dc08367cb935.png)

**Comment by ankiiitraj** [comment]
Hi @Rob--W, I was working on this issue. Can you guide me. Where(Directory) can I find `componentDidMount` ?

**Comment by ankiiitraj** [comment]
I have tried adding `document.addEventListener` on `/src/web/lib/components/Modal/index.js` and it is working fine.

**Comment by Rob--W** [comment]
The "Terms & Privacy" UI is here: https://github.com/mozilla/FirefoxColor/blob/17a2fdacd04eefb45c27dc6910de0d089bcd6669/src/web/lib/components/TermsPrivacyModal/index.js

It uses the Modal class from: https://github.com/mozilla/FirefoxColor/blob/17a2fdacd04eefb45c27dc6910de0d089bcd6669/src/web/lib/components/Modal/index.js

As you can see in the implementation, it is basically a function that returns a React element, which is not pure JavaScript. If you aren't familiar with React, see https://reactjs.org/docs/components-and-props.html and https://reactjs.org/docs/react-component.html

If you learn better by seeing example, take a look at https://github.com/mozilla/FirefoxColor/blob/17a2fdacd04eefb45c27dc6910de0d089bcd6669/src/web/lib/components/ThemeColorsEditor/index.js

**Comment by ankiiitraj** [comment]
Hi, @Rob--W I was trying addEventListener and it worked fine. But on clicking key there is an increasing lag(freeze) of page after every key down. 
I can't get why it is happening. Help me out. Thanks

**Comment by Rob--W** [comment]
@ankiiitraj Could you show your current code that causes the issue that you're describing? You could create a branch, commit your code and submit a pull request. You will be able to update the pull request later (e.g. to process review feedback) by pushing more commits to the branch. Github will then automatically update the pull request if the branch has been updated.

**Comment by ankiiitraj** [comment]
@Rob--W, I tried using `componentDidMount` but on doing this and then `npm start`, it says `compile failed`.

**Comment by ankiiitraj** [comment]
@Rob--W I have made a PR. Can you please assign yourself as the Reviewer. Thanks

**Comment by Rob--W** [comment]
It has probably failed due to a syntax error. Read the guides that I linked very carefully and try again. If you still see a failure, push your code to the branch and I'll review it.

Let's continue this conversation at your pull request, at https://github.com/mozilla/FirefoxColor/pull/859
