### ISSUE TITLE
"Privacy" and "Terms" links are not focused when navigating with "Tab" key

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#268]
**[Affected versions]:**
- Firefox 59.0.3 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.36 custom build) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Press the "Tab" key multiple times, until the focus goes to "Privacy" and "Terms" links.

**[Expected result]:**
- The links are focused.

**[Actual result]:**
- The focus skips "Privacy" and "Terms" links and jumps directly to "Cookies".

**[Notes]:**
- On Mac 10.13.3 the focus jumps from "Save" button to the "Info" button from the left side of the address bar.
- Attached a screen recording of the issue:
![focus by keyboard](https://user-images.githubusercontent.com/37875464/39694080-b53b0e18-51ee-11e8-9872-a282cf82d58e.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified that the issue is no longer reproducible on Mac 10.13.3, Windows 10 x64 and Arch Linux on latest Firefox (61.0.1) and latest Nightly (63.0a1) with latest "Firefox Color"(07/25/2018) version 1.0.1 custom build.

**Comment by aniketkudale** [comment]
Thanks @Softvision-AndreeaCupsa for the confirmation.
