### ISSUE TITLE
"Save" button is no longer active if you navigate to a website and return to "Firefox Color" page

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#277]
**[Affected versions]:**
- Firefox 59.0.3 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (0.0.36 custom build) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Make one change in the theme.
4. Navigate to any website in the same tab.
5. Return to "Firefox Color" page and observe the "Save" button.

**[Expected result]:**
- "Save" button is active.

**[Actual result]:**
- "Save" button is inactive.

**[Notes]:**
- This behavior is also reproducible if you close the "Firefox Color" tab and you reopen it. 
- Attached a screen recording of the issue:

![save button](https://user-images.githubusercontent.com/37875464/39813435-20f13d66-5399-11e8-9d3b-ebf6b3e5c013.gif)

**Comment by spoji** [comment]
Would a beforeunload javascript dialog to warn the user that "unsaved sata may not be saved" be an acceptable solution here? 

Note that it would show up only if the user do have a unsaved theme.
![image](https://user-images.githubusercontent.com/2171145/60684287-d0e68100-9e6a-11e9-8ddd-02582ed88384.png)

**Comment by rebmullin** [comment]
hey @caitmuenster, I could no replicate this issue. would you or QA like to confirm this before closing this?

**Comment by caitmuenster** [comment]
Thanks @rebmullin! I also wasn't able to reproduce this. I think it's ok to close.
