### ISSUE TITLE
"Undo" button has an inconsistent behavior if you refresh the "Firefox Color" page or navigate to a website and return

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#278]
**[Affected versions]:**
- Firefox 59.0.3 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.36 custom build) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Make 1 change to the theme.
4. Navigate to any website in the same tab.
5. Return to "Firefox Color" page and click the "Undo" button.

**[Expected result]:**
- The last changed is undoed. "Redo" button is active.

**[Actual result]:**
- The last change is still there. "Redo" button is active.

**[Notes]:**
- On a second click on "Undo" button a "Do you want to apply this custom theme?" pop-up is wrongly displayed.
- If you have more than 1 change, clicking the "Undo" button after the pop-up is dismissed by clicking "Yes" wrongly undoes all the last changes.
- If you have more than 1 change, clicking the "Redo" button after the pop-up is dismissed by clicking "No" wrongly redoes all the last changes.
- Also after refreshing the page clicking once on "Undo" button doesn't undo the last change, second click on "Undo" button wrongly displays the "Do you want to apply this custom theme?" pop-up. After the pop-up dismissal all changes are undoed/redoed as one.
- Attached a screen recording of the issue:

![inconsistent undo behavior](https://user-images.githubusercontent.com/37875464/39814068-8cf46c98-539b-11e8-9ab4-8bf3f63cc75c.gif)

**Comment by wresuolc** [comment]
The undo stack should be whacked if someone navigates away from the page

**Comment by lmorchard** [comment]
Going to look into this. I suspect we have some other unexpected behavior with undo/redo, too. I think we add items to the undo stack with *every* redux store change - which can include things that look like non-events like picking the same saved theme twice or selecting the same color from a picker.

**Comment by Softvision-AndreeaCupsa** [comment]
This issue and is no longer reproducible on Windows 10 x64, Mac 10.13, Arch Linux with the latest Firefox Color custom add-on (0.0.39) installed. The "Undo" and "Redo" buttons are no longer displayed after you refresh the "Firefox Color" page or navigate to a website and return.

Considering this I will close this issue.
