### ISSUE TITLE
Saved Themes are wrongly duplicated if you click "Undo" or "Redo" and save the theme again

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#279]
**[Affected versions]:**
- Firefox 59.0.3 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**

- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.36 custom build) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Make 1 change to the theme and click the "Save" button.
4. Make another change to the theme and click "Save" button.
5. Click "Undo" button.
6. Click "Save" button and observe the "Saved themes" section.

**[Expected result]:**
- Only the first 2 themes are added to the "Saved themes" section.

**[Actual result]:**
- The first theme is duplicated.

**[Notes]:**
- If you don't save at step 4, when you undo the change the "Save" button is inactive and displays the "Saved!" text
- Having a preset theme saved to "Saved themes" and then undoing changes until it is reached again, will make the "Save" button active, but clicking it doesn't add the theme to the "Saved themes" section.
- Attached a screen recording of the issue:

![duplicate themes](https://user-images.githubusercontent.com/37875464/39820446-8302f912-53ae-11e8-9762-b96b75b358a7.gif)

**Comment by rebmullin** [comment]
I could not replicate this issue and this is with the older UI so seems like okay to close. Please reopen if necessary.
