### ISSUE TITLE
"Firefox Test Pilot" hyperlink's color is wrongly changed with the same color set in "Tab Highlight Color"

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#280]
**[Notes]:**
- Changing the "Firefox Test Pilot" hyperlink with the "Tab Highlight Color" can be confusing, as its easy to mislead users into thinking that all hyperlinks will have that color.

**[Affected versions]:**
- Firefox 59.0.3 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (0.0.36 custom build) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Observe the color of "Firefox Test Pilot" hyperlink.

**[Expected result]:**
- The text of the hyperlink is black.

**[Actual result]:**
- The hyperlink has the same color as the "Tab Highlight Color".

**[Additional Notes]:**
- Changing the "Tab Highlight Color" will change "Firefox Test Pilot" hyperlink's color.
- Attached a screen recording of the issue:

![hyperlink color](https://user-images.githubusercontent.com/37875464/39822243-c74d974a-53b2-11e8-938d-3510ec9ede67.gif)

**Comment by lmorchard** [comment]
[I think this is an intentional design feature @johngruen added](https://github.com/mozilla/FirefoxColor/pull/272)
