### ISSUE TITLE
Gradient theme texture appears cut off if "Toolbar Color" opacity is under 50%

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#285]
**[Affected versions]:**
- Firefox 60 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (0.0.36 custom build - 15/05/2018) installed from the "about:debugging" page.
- "Toolbar Color" opacity is set to 50%.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Select a gradient theme texture.
4. Observe the background color of the toolbar. 

**[Expected result]:**
- The theme texture is properly displayed.

**[Actual result]:**
- The theme texture appears cut off.

**[Additional Notes]:**
- Gradient theme texture is also wrongly displayed in "Preview Panel"
- The lower the value of opacity, the more noticeable the issue is.
- This issue is more noticeable if the "Bookmarks toolbar" is active. 
- Attached a screen recording of the issue:

![screen recording of the issue](https://user-images.githubusercontent.com/37875464/40046494-c841589e-5835-11e8-8639-0c4b19201463.gif)

**Comment by johngruen** [comment]
Oh yeah, i guess those textures aren't quite tall enough...this should be an easy fix.

**Comment by johngruen** [comment]
With the added tab space and bookmark menu, i was able to make my browser 104px tall, let's keep everything that is only meant to repeat-x

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue on Mac 10.13 and Win 10 x64 on Latest Firefox (60.0.1) and Latest Nightly (62.0a1) with latest "Firefox Color" (0.0.37 22/05/2018) installed.

The gradient theme texture is properly displayed now if the "Bookmark toolbar" is enabled, but the gradient theme texture is still wrongly displayed in the "Preview Panel". 

On Win 10 x64 the gradient texture theme is still cut off if you have enabled the "Bookmark toolbar" and the "Menu Bar".

Considering this i will reopen this issue.

I attached a screenshot of the issue:

![firefox color gradient issue](https://user-images.githubusercontent.com/37875464/40363483-53ffa92e-5dd8-11e8-9c58-8e867ebbe229.jpg)

**Comment by johngruen** [comment]
oy vey

**Comment by Softvision-AndreeaCupsa** [comment]
I looked over this and the gradient theme texture is correctly displayed in the browser's UI, but is still wrongly displayed in the "Preview Panel". 

Are we ok with the "Preview Panel" looking like this?

I attached a screenshot of the "Preview Panel":

![preview panel gradient issue](https://user-images.githubusercontent.com/37875464/40419511-421a3696-5e8e-11e8-8920-1daf0f8e5720.png)

**Comment by johngruen** [comment]
yeah we can reopen and fix this

**Comment by Softvision-AndreeaCupsa** [comment]
Considering the comments above I will reopen this.

**Comment by rebmullin** [comment]
Seems like this is an older version of FF color. @caitmuenster ,ok to close this one?

**Comment by caitmuenster** [comment]
@rebmullin Yeah, this one is good to close!
