### ISSUE TITLE
"Copy and paste this URL to to share your creation" text has an extra "to"

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#287]
**[Affected versions]:**
- Firefox 60 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**

- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.37 custom build 16.05.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Observe the subtitle of "Share your theme".

**[Expected result]:**
- "Copy and paste this URL to share your creation" text is displayed.

**[Actual result]:**
- "Copy and paste this URL to to share your creation" text is displayed.

**[Notes]:**
- Attached a screenshot of the issue:

![issue extra to](https://user-images.githubusercontent.com/37875464/40123913-f9c508e8-592f-11e8-8c2e-4fde3dae62f1.png)

**Comment by johngruen** [comment]
Strings aren't final atm, this should get fixed soon
