### ISSUE TITLE
How to edit console color theme?

### ISSUE THREAD

**Issue by quantumproducer** [mozilla/FirefoxColor#299]
I'm on OSX, and my computer doesn't have a "userchrome.css" file anywhere.

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @quantumproducer,

This repository is tracking the work that is done as a part of the Firefox Color feature, which to the best of my knowledge has nothing to do with the console color theme. However, you can switch from Light to Dark themes for the Developer Tools by pressing F12 and then F1. You should then see two radio buttons with Dark and Light.

I'm not sure how the issue's description is related to Firefox Color, but a "userChrome.css" file is something a user creates in:
\Users\username\Library/Application Support/Firefox/Profiles/profileinuse. Where you should create an additional folder called "chrome" and place your "userChrome.css" file there.

I hope this answers your question.

**Comment by quantumproducer** [comment]
Thanks @SoftVision-CiprianMuresan , I will try that. 
Is there a way to click for those themes instead of with FN keys?

**Comment by quantumproducer** [comment]
@SoftVision-CiprianMuresan know where I can find a big list of userChrome.css documentation settings?

**Comment by SoftVision-CiprianMuresan** [comment]
F12 is the general shortcut for the Developer Tools. Individual Tools can also be accessed from Tools -> Web Developer. After which you click the "..." button ("Customize Developer Tools and get help) and then select "Settings". You should land in the same place as the F12, F1 combo.

The best link I can offer for userChrome documentation is: https://www.userchrome.org/how-create-userchrome-css.html. (However, I'm not an expert on this)
