### ISSUE TITLE
Backfill tests?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/FirefoxColor#301]
We should add some unit tests to the project, now that the functionality seems to be settling down. 

Tests are run using the `npm test` command and our testing framework consists of these parts:
* [mocha](https://mochajs.org/) - for organizing and running test cases
* [chai](http://www.chaijs.com/) - for making assertions about the results of tested code
* [sinon](http://sinonjs.org/) - for creating mock functions and modules
* [mock-require](https://github.com/boblauer/mock-require) - for replacing real modules with testing code
* [enzyme](https://github.com/airbnb/enzyme/blob/master/docs/guides/mocha.md) - for rendering React components in tests

We haven't added enzyme to the project yet, but that's coming next

**Comment by lmorchard** [comment]
I may even do this as a part of issue #286, so I can wrap the theme comparison function in some unit tests to try to reproduce the issue

**Comment by lmorchard** [comment]
Another small todo - add test coverage metrics. It looks like it's pretty easy to do with mocha and nyc:

https://istanbul.js.org/docs/tutorials/mocha/

**Comment by Shruti9520** [comment]
Hi there! @lmorchard 
I would like to take this up. :-)

Thank you!

**Comment by Shruti9520** [comment]
Hi @lmorchard 
I wrote very basic tests for-
1. AppHeader Component- https://gist.github.com/Shruti9520/7059e5b574ce8e8ac74a69a6fb8399d9
2. AppFooter Component- https://gist.github.com/Shruti9520/f4f4bb9ea8e3cdcbac4666db521a8d20
Here I want to add tests after click event. For this, let's say here- https://github.com/mozilla/FirefoxColor/blob/b8e3ece761f2caed2ef9237f355d9b2a54c853e2/src/web/lib/components/AppFooter/index.js#L37, I want to add a test. So for this, I will be adding a mock function like this -https://github.com/mozilla/FirefoxColor/blob/b8e3ece761f2caed2ef9237f355d9b2a54c853e2/src/lib/metrics.js#L250 method and will use sinon.spy() for this. Is that fine?
3. AppBackground- https://gist.github.com/Shruti9520/ca1322c0b31ada4ccc7ba876a13f5151
