### ISSUE TITLE
Allow users to revert to default themes with FF color installed

### ISSUE THREAD

**Issue by weivicky** [mozilla/FirefoxColor#302]
For example, I change my theme back to default and exit my browser. When I reopen my browser, it changes back to my last used Firefox Color theme

![may-22-2018 14-02-20](https://user-images.githubusercontent.com/10877399/40381137-e93eacfc-5dc8-11e8-900c-b08dc68a64f4.gif)

**Comment by lmorchard** [comment]
> How difficult it is to change the hierarchy?

As far as I understand, it's impossible to change from Firefox Color or any other dynamic theme. It's an upstream issue with how things are implemented within Firefox itself.

**Comment by johngruen** [comment]
I think there could be a fix for this if we bring back some kind of **restore default** button that would call `browser.theme.reset()` we'd have to add a prop that would override theme colors and backgrounds.

**Comment by johngruen** [comment]
Okay this might not work

**Comment by lmorchard** [comment]
> I think there could be a fix for this if we bring back some kind of restore default button that would call browser.theme.reset()

That was issue #44, closed because `browser.theme.reset()` doesn't do what we want here.

**Comment by nt1m** [comment]
There's going to be a discussion at the all hands about dynamic themes (and Firefox Color is one of them), and how it interacts with other built-in themes in Firefox. There's also going to be a meeting pre-all hands, so let me know if you're interested in joining.

**Comment by caitmuenster** [comment]
Hey @nt1m (or @lmorchard or @johngruen) do you know if this is technically doable?

**Comment by nt1m** [comment]
It's probably possible by watching the [management events](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management#Events) and then storing a value everytime the theme changes. Then if that value is found in storage when Firefox color starts up, we can avoid calling `browser.theme.update()`.

**Comment by nt1m** [comment]
There should probably be an easier way to do this, but that should work fine.

**Comment by caitmuenster** [comment]
Here's the current plan for moving forward with this issue: 

**Plan A**
_Note: this represents the "ideal" path forward and assumes that Color can use the theme that had been active prior to installing Color as the starting point for modifications._

1. User installs Color 
2. [Onboarding modal](https://docs.google.com/presentation/d/1didhbY1yUYAXUaj3Vg2unMt-iDgK9FU4Kn7ceS8KHDo/edit#slide=id.g6039a93c3e_0_56) runs 
3. At the end of the modal, the user's active theme does not change until the user starts interacting with the Color UI. 
4. User can click a "Revert All" button at any time to revert back to last active theme. 

**Plan B**
_If Color can't use the last active theme before install as a starting point, we'll go with this flow._

1. User installs Color
2. [Onboarding modal](https://docs.google.com/presentation/d/1didhbY1yUYAXUaj3Vg2unMt-iDgK9FU4Kn7ceS8KHDo/edit#slide=id.g6039a93c3e_0_56) runs 
3. At the end of the modal, the user's active theme changes to the "starting canvas." 

![Screen Shot 2019-10-04 at 2 03 49 PM](https://user-images.githubusercontent.com/23342476/66239885-d8a70300-e6af-11e9-8b61-f1aad247c882.png)

4. The theme changes when the user interacts with the Color UI. 
5. User can click "Revert All" to return to the last theme that had been active before they installed Color.

**Comment by rebmullin** [comment]
@caitmuenster, thanks for the above:) 

I have a few follow up questions:

1. Do you have the image for the paint brush icon - the center image in the last slide?

2. Regarding the "revert all" placement - 
[](https://monosnap.com/image/ArnxnoqNugSZDXv2eHn3lbVzfepOzQ.png) - is this where we want to add this?

**Comment by caitmuenster** [comment]
>     1. Do you have the image for the paint brush icon - the center image in the last slide?

Yes! I grabbed it from [src / images / logo-white.svg](https://github.com/mozilla/FirefoxColor/blob/master/src/images/logo-white.svg). :) 

>     2. Regarding the "revert all" placement -

Yeah, I think it makes sense to put it there! We can also use the Forget button from the [Photon style guide ](https://design.firefox.com/icons/viewer/#) for the button.

**Comment by rebmullin** [comment]
> Yes! I grabbed it from src / images / logo-white.svg. :)
🤦‍♀ 

> Yeah, I think it makes sense to put it there! We can also use the Forget button from the Photon style guide for the button.
thank you:) 👍

**Comment by caitmuenster** [comment]
This is currently blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1592831.

**Comment by rebmullin** [comment]
hey @caitmuenster, do you still want me to update the onboarding slides or should we keep that update with this work?

**Comment by caitmuenster** [comment]
@rebmullin Let's still update the onboarding slides and push them when they are ready. Once the Firefox bug is fixed, we can come back to the bits about reverting themes. :) 

(Sidenote for anyone who is interested in contributing code to Firefox: bug [1592831](https://bugzilla.mozilla.org/show_bug.cgi?id=1592831) is a good first bug and @Rob--W is onboard to mentor it! Check out the bug for details on how to get started.)

**Comment by rebmullin** [comment]
looks like bug [1592831](https://bugzilla.mozilla.org/show_bug.cgi?id=1592831) is fixed. I am unblocking this :)
