### ISSUE TITLE
Feature Idea: Right-click on Image to start making a theme

### ISSUE THREAD

**Issue by sevaan** [mozilla/FirefoxColor#306]
If a user sees a cool image in their browser while surfing, it would be awesome if they could right-click on it, and somewhere in the context menu is an option that allows them to start creating a theme with that image as the toolbar background.

**Comment by lmorchard** [comment]
FWIW, we don't / can't support user-supplied images right now. There's a canned set of backgrounds embedded in both the website and the add-on - the background is just set via an ID passed between the two. So, we'd need to work out managing user-generated images, which might be more of a job for a site like addons.mozilla.org

**Comment by lmorchard** [comment]
Issue #308 is probably a blocker for this fwiw
