### ISSUE TITLE
Let users add images to FF color

### ISSUE THREAD

**Issue by johngruen** [mozilla/FirefoxColor#308]
In order to replace and  enhance the feature set of personas plus we should let users add images to their themes. 

Users should be able to do the following:
1. Add multiple image to their themes
2. Set the stacking order of these images (which one is on top)
3. Set the repeat pattern of each image (`no-repeat`, `repeat-x` etc)
4. Set the registration of each image (`center top`,  `bottom left` etc)

**Comment by lmorchard** [comment]
This could be a bit of a challenge to figure out. The way Firefox Color works right now is that there's a canned set of images baked into both the add-on and the website. They're selected by name in the theme data shared between the two.

Not sure how to support arbitrary user images in Firefox Color under that model. I don't think WebExtensions have access to the local filesystem, so it doesn't look like we can reference an image that way. We might be able to host the images on our servers and reference them in the theme via HTTPS URL, but I have a hunch that's not allowed.

In fact, my main hunch is that the only real way to let users add their own images to a theme is to basically generate a new standalone theme add-on with the images backed in (i.e. issue #93)

**Comment by lmorchard** [comment]
Also, in terms of UX, if we can't access user-supplied images in the Firefox Color add-on - we can't do the kind of live preview of changes involving those images in browser chrome like we do with every other property in the editor right now.

**Comment by lmorchard** [comment]
> Like I said, I'd be surprised if data: URIs work. Need to give it a try and experiment

Hmm, I may need to eat my hat - data URIs might work! Will do more investigation

**Comment by johngruen** [comment]
@lmorchard there's a lot going on in this spec, but here's a [representation](https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/Updated_FF_Color/#artboard4
) of how  the image picker UI should work.
 
Don't worry about most of this spec for this issue...just on the image picker component itself. 

As for the larger design overhaul, I've got a branch going that we can slot the image picker component into once it's ready.

**Comment by johngruen** [comment]
Oh and SVG assets are here: https://github.com/mozilla/testpilot-assets/tree/master/ThemesRFun/00_Assets

**Comment by lmorchard** [comment]
Looks like we're missing some SVG assets. I see `icon_align_center` (vertical center align) and `icon_align_left`. 

But, it seems like we missing things like `icon_align_right`, `icon_align_horizontal_center`, `icon_align_top`, `icon_align_bottom`, `icon_close`, `icon_warning`. Making up the names there, but you probably get the gist. Going to try going ahead with the icons I have as stand-ins, but would be good to get better SVGs than try to hack them myself.

**Comment by lmorchard** [comment]
FWIW, I was able to make the two existing icons work by way of some CSS transforms to rotate & flip
