### ISSUE TITLE
TRF installers should be informed of Test Pilot

### ISSUE THREAD

**Issue by johngruen** [mozilla/FirefoxColor#31]
If a user installs TRF from the TRF website, they should be prompted to check out test pilot.

**Comment by lmorchard** [comment]
Something that might need figuring out: If the user is viewing a theme that got shared with them, and they want to install TRF to get that theme - how do they get back to that theme if we send them away to Test Pilot?

**Comment by youwenliang** [comment]
I think John was saying not redirecting to Testpilot but to show a link to testpilot so that it won't break the process.

**Comment by johngruen** [comment]
@lmorchard yeah, sorry the title here was a bit vague, @youwenliang is right.

**Comment by youwenliang** [comment]
I think we can have something like an oboarding tour image when people install TRF through the TRF website. They can click learn more to visit the TRF detail page in Test pilot website.
![final_receiver_with extension02](https://user-images.githubusercontent.com/8919308/35953945-1d3e0faa-0cc2-11e8-9b0c-865545128b1a.png) (Slide 1)

And if the link they visited is from other users, they can still apply the theme others created after seeing the onboarding image:
![final_receiver_with extension02 copy](https://user-images.githubusercontent.com/8919308/35954055-90eff4fe-0cc2-11e8-9a94-9c1309e1186c.png) (Slide 2)

**Comment by johngruen** [comment]
@youwenliang i think we would apply the theme already as part of the install process since they've already opted in...

**Comment by youwenliang** [comment]
@johngruen yes you are right. We can just have the 1 slide onboarding to direct people to Test Pilot.

**Comment by 94151** [comment]
@lmorchard I would like work on this.

**Comment by lmorchard** [comment]
I think this issue is still fair game

**Comment by johngruen** [comment]
Closing this, since it gets rolled up into onboarding
