### ISSUE TITLE
The "Install Firefox Color" button wrongly redirects to a "404" page

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#314]
**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "https://color.firefox.com" page.
3. Click the "Install Firefox Color" button from the top part of the page.
4. Observe the behavior.

**[Expected result]:**
- The add-on is correctly installed.

**[Actual result]:**
- You are redirected to the "https://testpilot.firefox.com/files/themesrfun@mozilla.com/signed-addon.xpi" page.

**[Notes]:**
- If you change the "themesrfun" string from the above URL with the "FirefoxColor" one, the add-on is correctly installed.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40721894-8116da9e-6423-11e8-9620-966b03fc139d.gif)

**Comment by jbuck** [comment]
Ah, I hadn't enabled building automatically in production yet, so prod was on an old build from may 9th. I enabled that, and it's pointing at the right addon now

**Comment by wresuolc** [comment]
Closing based on jbuck's last comment

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Color" add-on (0.0.38) installed from the "https://color.firefox.com/" website.
Verified on Windows 10 x64, Ubuntu 16.04 x64 and Mac 10.13 with the latest Firefox release (60.0.1) and latest Nightly (62.0a1 - 20180530220105).
