### ISSUE TITLE
The "Firefox Color" survey can wrongly be finalized without completing any fields from the form

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#323]
**[Notes]:**
- The main concern here is that we could receive empty feedbacks and it could be hard to know if the feedback was empty from the start or if the information was lost due to other factors.

**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Color" add-on (1.0.0 custom built on 04.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "https://color.firefox.com" page.
3. Click the "Feedback" button and press the "Next" button from the newly opened page.
4. Observe the behavior.

**[Expected result]:**
- Error messages appear next to all fields.

**[Actual result]:**
- The survey is finalized and you are redirected to the "Thank you" page.

**[Additional Notes]:**
- This issue is not reproducible with the "Send" or "Firefox Notes" survey pages.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40920490-640f6fec-6815-11e8-8903-2293f091b315.gif)

**Comment by johngruen** [comment]
Resolved

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Color" add-on (1.0.1) installed from the "https://color.firefox.com/" website.
Verified on Windows 10 x64, Ubuntu 16.04 x64 and Mac 10.13 with the latest Firefox release (60.0.1) and latest Nightly (62.0a1 - 20180604220149).
