### ISSUE TITLE
The legibility of the URL in the toolbar field popup

### ISSUE THREAD

**Issue by weivicky** [mozilla/FirefoxColor#327]
Right now, the url color is defaulted as blue. Could be illegible if the user changes to blue, for example...

Couple of possible solutions: 
- the system changes the url color automatically
- we give users the ability to change it
- we ignore it...

**Comment by johngruen** [comment]
So, we might consider putting guard rails to keep people from setting bg colors where foreground colors cannot be changed to prevent them from making una11y themes. 

Alternately we could add an API change.

**Comment by nt1m** [comment]
Vivaldi has a "contrast adjustment" setting, which would change the colors to the nearest accessible ones. 
<img width="237" alt="screen shot 2018-06-05 at 10 48 57 pm" src="https://user-images.githubusercontent.com/1795135/41004744-e0e3cd26-6912-11e8-8421-e024e793b4a4.png">

Alternatively, Chrome has a a11y contrast white line in their DevTools color picker.
https://remysharp.com/2017/08/17/contrast-ratio-in-devtools

@johngruen What were you thinking of in terms of API change ?
