### ISSUE TITLE
Cannot check /__version__ endpoint on stage or prod

### ISSUE THREAD

**Issue by pdehaan** [mozilla/FirefoxColor#343]
Currently trying to visit https://color.stage.mozaws.net/__version__ or https://color.firefox.com/__version__ tries to download the content instead of rendering it as JSON.

All 3 envs (dev/stage/prod) all seem to point to 2c3238c901e57a3012a436b7fc256a4b6ffb4ffc

**Comment by lmorchard** [comment]
Sounds like we could use a `Content-Type: application/json` on `__version__` so a browser handles them better but the resources are actually there.

@jbuck is there an easy way to slap that header on `__version__`?

**Comment by jbuck** [comment]
@lmorchard yep, I can add that. Is there anywhere else the upload process isn't setting the content-type correctly? 

I've got a PR up to fix just `__version__` https://github.com/mozilla-services/cloudops-deployment/pull/2093/files

**Comment by lmorchard** [comment]
> Is there anywhere else the upload process isn't setting the content-type correctly?

Not that I know of, but everything else seems to be fine so far

**Comment by jbuck** [comment]
This works correctly now
