### ISSUE TITLE
Theme texture not applied to Tab Center Redux

### ISSUE THREAD

**Issue by Keith94** [mozilla/FirefoxColor#344]
[Tab Center Redux](https://addons.mozilla.org/en-GB/firefox/addon/tab-center-redux/),  a WebExtension that supports theme integration, is not affected by the "Theme Texture" setting on https://color.firefox.com; i.e., the background of the tabs always have the plain, untextured look. All the other settings are applied except for Theme Texture. Is it possible to add support for it?

**Comment by lmorchard** [comment]
> Is it possible to add support for it?

Color doesn't have the ability to impose a theme on other add-ons. The support would need to be added from the Tab Center Redux side. 

The way this would work is that the new Theme API used by Firefox Color offers a [`theme.getCurrent()` method](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/getCurrent). Tab Center Redux (and other add-ons) could use that method to grab the current theme properties and apply them to itself accordingly.

Going to close this for now, but I think Mozilla will work toward addressing this issue more generally for the Theme APIs. That's a bigger thing than Firefox Color itself.
