### ISSUE TITLE
"Firefox Color" website is wrongly displayed as not being installed after restarting the browser while focusing another tab

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#347]
Also logged in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1467432
***

**[Affected versions]:**
- Firefox 62.0a1

*[Affected Platforms]:*
- All Windows
- All Mac
- All Linux

*[Steps to reproduce]:*
1. Open Firefox Nightly 62.0a1 (2018-06-06).
2. Navigate to https://color.firefox.com.
3. Click the "Install Firefox Color" button and follow the flow in order to succesfully install "Firefox Color".
4. Focus another tab and restart the browser.
5. Focus the "Firefox Color" tab and observe the page.

**[Expected result]:**
- The "Firefox Color" website is properly displayed as being installed.

**[Actual result]:**
- The "Install Firefox Color" button is displayed, despite the add-on being installed.

**[Notes]:**
- This issue is not reproducible on Firefox Release(60.0.2) or older versions of Firefox Nightly.
- This seems to be a Firefox regression and after some further investigation I have found the following regression range:
10:49.58 INFO: Last good revision: 6646425c8cd10440f2ce38cd594be0c84a7c21fa
10:49.58 INFO: First bad revision: f6c89ca4944b0233e08463ce4825812c1b08373c
10:49.58 INFO: Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=6646425c8cd10440f2ce38cd594be0c84a7c21fa&tochange=f6c89ca4944b0233e08463ce4825812c1b08373c
- Attached a screen recording of the issue:

![screen recording of the issue 2](https://user-images.githubusercontent.com/37875464/41098227-580bca06-6a63-11e8-8366-c8e179b423b1.gif)

**Comment by johngruen** [comment]
@Softvision-AndreeaCupsa can you check this again soon?

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible, verified on latest Nightly 62.0a1 (2018-06-19) (64-bit), on Windows 10 64bit, Mac 10.13 and Arch Linux. Considering this and the fact that the upstream bug is also fixed I will close this issue.
