### ISSUE TITLE
FF Color settings desappear

### ISSUE THREAD

**Issue by swingwolf** [mozilla/FirefoxColor#351]
Hi,
FF color don't run. Run at Firefox 64 bits (60.0.2) start up and immediately all FF color's settings disappear.

**Comment by Softvision-AndreeaCupsa** [comment]
Can you please provide more information about the steps you are following, maybe attach a screenshot of the issue?

**Comment by swingwolf** [comment]
Hello,

Eureka, I found: it is the extension "colorfultabs" which is incompatible and delete all the themes used in my settings (classics theme or FF color). 

Attached 1= FF 60.0.2 + ColorfulTabs and lucky bamboo theme

Attached 2 idem but ColorfulTabs disabled.

Regards.

 

De : Softvision-AndreeaCupsa <notifications@github.com> 
Envoyé : vendredi 8 juin 2018 13:06
À : mozilla/FirefoxColor <FirefoxColor@noreply.github.com>
Cc : swingwolf <swingwolf@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [mozilla/FirefoxColor] FF Color settings desappear (#351)

 

Can you please provide more information about the steps you are following, maybe attach a screenshot of the issue?

**Comment by Softvision-AndreeaCupsa** [comment]
@thanks swingwolf
According to the comment above I will close this issue.
