### ISSUE TITLE
Firefox Color website doesn't recognize the extension

### ISSUE THREAD

**Issue by ianb** [mozilla/FirefoxColor#352]
I tried clicking on the link from [this reddit post](https://www.reddit.com/r/firefox/comments/8piocj/color_adapatalike/) going to [here](https://color.firefox.com/?theme=XQAAAALzAAAAAAAAAABBqYhm849SCiazH1KEGccwS-xNVAVL4BQvynlSOhZDnhNp34wJL2A4t3RbmZDnuBOWF5y8L-ifqL5Zay6-5XLe3p98eWKb7x-f5TId4gAo64-iAFOo-n9u_emGNmAfPJH7G2DJyM2_cGnYeKY8krWgOZYOpu7DJInboDN7b6yjSZz3zcfITcCsyUuAd92fxKgsUcRolzkcDrcWZpfC4L4ElR0Ak1t5x0gGYOZlMXd8bpAR9j__245AAA), I ended up getting a request to install Color (which I already have installed), and I couldn't preview themes on the site. (Probably those links don't particularly matter, it's just when I noticed it).

I'm not seeing anything in the browser console when I visit a color site. When I try a theme change I do see `Sending 'theme-change' 'select-full': 
Object { ... }` in the page console, but it doesn't do anything.

When I go to debug the background page (via about:debugging) I see this in the console:

![image](https://user-images.githubusercontent.com/44390/41170914-0c7208b0-6b14-11e8-9372-747dd0b574fc.png)

I'm guessing the browser experiment isn't available or working? I can't tell where `browser.experiments.settings` comes from, it doesn't seem to be in this codebase. If I try to click on `background:17:5` I get `Source map error: TypeError: NetworkError when attempting to fetch resource. Resource URL: moz-extension://a546179a-06ba-9a4a-afc2-51871c45ac2f/background.js
Source Map URL: background.js.map`

I'll restart the browser and see what happens. **Update:** a restart did fix it. I'll see if it keeps working. Not the old style stayed applied even while updating was broken. We might be having similar problems with our experiment in Side View.

**Comment by lmorchard** [comment]
> (which I already have installed)

From where did you install the add-on? Also, if you look in about:addons, what is the name of your installed Color add-on? 

If you didn't originally install the add-on from color.firefox.com, you might have a version from a different deployment of the site (eg. dev on github pages). Each deployment of the site has a site-specific build of the add-on

> When I go to debug the background page (via about:debugging) I see this in the console:

I don't think any of those errors are from Color. [We don't use `browser.experiments.settings` in Color](https://github.com/mozilla/FirefoxColor/search?q=browser.experiments.settings&unscoped_q=browser.experiments.settings) as far as I'm aware.

**Comment by ianb** [comment]
I installed the add-on from testpilot.firefox.com. It was working find with the color.firefox.com site before, and did again after restart. It seems like color.firefox.com didn't detect the add-on was installed due to something that happened/broke in my browser session.

**Comment by Softvision-AndreeaCupsa** [comment]
This issue seems similar to the one I logged: https://github.com/mozilla/FirefoxColor/issues/347.
It seems to be an upstream issue rather than a Firefox Color one.
Attached a link to the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1467136

**Comment by johngruen** [comment]
@ianb can you test again when you're off PTO. I'll close this for now since we think it's resolved upstream
