### ISSUE TITLE
[Feature request] Change theme based on Container

### ISSUE THREAD

**Issue by malore** [mozilla/FirefoxColor#356]
I'd like if it would be possible to create a theme for every container so that it would change accordingly to the active tab container. Something like [Containers Theme](https://addons.mozilla.org/en-US/firefox/addon/containers-theme/?src=collection), but more powerful.

**Comment by johngruen** [comment]
Hey @malore this feature isn't on our roadmap, but fortunately [this addon](https://addons.mozilla.org/en-US/firefox/addon/containers-theme/?src=search) already has you covered!
