### ISSUE TITLE
Consider passing color values in URL rather than hash

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/FirefoxColor#37]
That'd make it a lot easier to do colorspace analysis.

**Comment by lmorchard** [comment]
Can you elaborate on what you mean? The theme is currently a compressed JSON object encoded as base64 in the URL param - it's not using the hash

**Comment by lmorchard** [comment]
Oh, you mean serialize the JSON as set of URL parameters? (By hash, I thought you meant the fragment identifier #hash) I tried doing that at one point, but the URL handling got kind of gnarly. We can take another swing at it, though. This is the kind of data we'll have to serialize/deserialize, maybe need to work on munging property names a bit to reduce length:

```json
{
 "images": "",
 "colors": {
  "toolbar": {
   "h": 0,
   "s": 50,
   "l": 50,
   "a": 100
  },
  "toolbar_text": {
   "h": 0,
   "s": 0,
   "l": 0
  },
  "accentcolor": {
   "h": 0,
   "s": 0,
   "l": 0
  },
  "textcolor": {
   "h": 0,
   "s": 0,
   "l": 0
  },
  "toolbar_field": {
   "h": 0,
   "s": 0,
   "l": 0,
   "a": 100
  },
  "toolbar_field_text": {
   "h": 0,
   "s": 0,
   "l": 100
  }
 }
}
```

**Comment by lmorchard** [comment]
FWIW, alternatively, we could ping some metrics service with the de-serialized theme data directly

**Comment by johngruen** [comment]
Could we do something like trf.com/?a=ffccaa&b=ccaabb&c=aaffaa...?

**Comment by lmorchard** [comment]
I think the format would depend on exactly how and where we want to do the color metrics. 

And also how often do we want to record it - because the URL changes for every change the user makes to the theme. Would it be better to record the theme at more significant points? (e.g. when sharing out or receiving a shared theme?)

**Comment by johngruen** [comment]
I added these as custom dimensions using HSL(A) values passed in as CSVs. The idea would be that this format would be the easiest to parse in a big SQL table, but it might be no different to send them as HEX or HEXa

**Comment by lmorchard** [comment]
So, does that look at the URL (and so we change the URL format) or do we ping it from JS?

**Comment by lmorchard** [comment]
But, I'm saying we might not even need to tweak the URL if we use something else to measure this (i.e. pings from JS with the measurement protocol)

**Comment by lmorchard** [comment]
Also FWIW, looks like #11 would be a good place to hash this out from the metrics specs side and #46 for implementation side

**Comment by johngruen** [comment]
Reopening this for consideration...some of the feedback from Sharon's ur was that the URLs seemed really opaque to people....

I wonder if we just use hex(a) in all the preset themes, we could get more terse/understandable with the theme urls (`?c=ffaaff22,22ccaa,eeffee...&bg=bg-001.svg`)

**Comment by wresuolc** [comment]
Using hex values in the URL can up to triple the length according to our conversation (the current URL zips the json).  We'll reclose for now.

**Comment by chuckharmston** [comment]
I made a suggestion to John that might be helpful here: what if, when a user tries to get a URL to share, you return a short url? `fxcol.org` is available and could be reasonably added to our enterprise bit.ly account. A Lambda function could be used to bridge a theme hash => short URL via the bitly API.
