### ISSUE TITLE
Minor capitalization typo in Firefox Color Survey

### ISSUE THREAD

**Issue by papernapkinhead** [mozilla/FirefoxColor#373]
Steps:
- Disable the Firefox Color add-on
- Opt to take the survey

Result:
- The first survey question has a response "It didn't do what i wanted it to do" (see attached)

Expected:
- "It didn't do what I wanted it to do" (with a capital 'i')

![2018-07-17 at 9 17 am](https://user-images.githubusercontent.com/589409/42831183-7fb1b878-89a2-11e8-8eea-d9f4c69c66c8.jpg)

**Comment by teonbrooks** [comment]
this has now been corrected

**Comment by papernapkinhead** [comment]
Looks great!

<img width="326" alt="image" src="https://user-images.githubusercontent.com/589409/43166359-3b0023aa-8f4b-11e8-9016-a48d2ba37ac4.png">
