### ISSUE TITLE
Add list of links in page footer to privacy doco

### ISSUE THREAD

**Issue by lmorchard** [mozilla/FirefoxColor#39]
From [acceptance criteria](https://github.com/mozilla/ThemesRFun/blob/master/docs/acceptance.md):

> - [ ] It should have a list of mandatory links at the bottom of the page including any required privacy documentation.

**Comment by Paarmita** [comment]
@lmorchard Is this issue still open?

**Comment by 94151** [comment]
@lmorchard is this issue still active can i work on this?

**Comment by lmorchard** [comment]
This is actually no longer a good first contributor issue - we have links now, but we actually need to add the privacy documents from the legal department
