### ISSUE TITLE
Menu's are not themed

### ISSUE THREAD

**Issue by zynexiz** [mozilla/FirefoxColor#396]
I use a dark desktop, and the default dark theme with Firefox. Installing and activating this plugin makes Firefox "light" again, meaning the menus and popups are still white. Deactivating the plugin reverse it back to the standard theme, and my menus and popups are dark again.

Since Firefox Quantum 60, it looks like menus and popups can be themed to match the rest (tried some dark themes that do this). It's described here; https://hacks.mozilla.org/2018/07/dark-theme-darkening-better-theming-for-firefox-quantum

The ability to change the colours described there should be added to make the experience better.

**Comment by johngruen** [comment]
Yep, we are currently working a new ux that will allow this

**Comment by johngruen** [comment]
https://github.com/mozilla/FirefoxColor/issues/325
