### ISSUE TITLE
The "Save" button no longer saves set themes and does not change into "Saved!"

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#397]
**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (1.0.1 custom build 08/24/2018)
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Make one change to the theme.
4. Click the "Save" button and observe the behavior. 

**[Expected result]:**
- A new section with saved themes is displayed and the set theme is added to that section.
- The button becomes inactive and the text is changed into "Saved!"

**[Actual result]:**
- No new section is displayed.
- The hover effect remains after the button was clicked. 

**[Notes]:**
- Attached a screen recording of the issue:

![rec of the issue - save button](https://user-images.githubusercontent.com/37875464/44574003-d118e900-a790-11e8-8921-5d68a5c0ebb7.gif)

**Comment by lmorchard** [comment]
I'm having trouble reproducing this issue. I follow the steps, but the Save button works for me every time. I wonder if we have fixed this issue? Or if there are other factors causing it?

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible on Mac 10.13, Windows 10 x64 and Arch Linux on latest Nightly (64.0a1) with latest "Firefox Color" (1.1.0 dev version/ 12/09/2018) installed.
Considering this I am closing this issue.

**Comment by lmorchard** [comment]
Thank you for verifying!

**Comment by Softvision-AndreeaCupsa** [comment]
Sorry for taking so long to verify these issues.
