### ISSUE TITLE
"Complementary" and "Random" buttons do not lose their hover effects after they are clicked

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#398]
**[Affected Platforms]:**
- All Windows
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (1.0.1 custom build 08/24/2018)
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Click the "Complementary" button and move the mouse away.
4. Observe the button.

**[Expected result]:**
- The button has no effect.

**[Actual result]:**
- The button has a hover effect.

**[Notes]:**
- This issue is also reproducible with the "Random" button.
- This issue is not reproducible on Mac.
- Attached a screen recording of the issue:

![rec of the issue - hover effect](https://user-images.githubusercontent.com/37875464/44575281-52be4600-a794-11e8-8040-b46f434157f5.gif)

**Comment by johngruen** [comment]
Close this in favor of my new UI branch
