### ISSUE TITLE
A few button tooltips wrongly start with lowercase letters

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#399]
**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (1.0.1 custom build 08/24/2018)
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Hover the "Complementary" button.

**[Expected result]:**
- "Generate complementary theme" tooltip is displayed.

**[Actual result]:**
- "generate complementary theme" tooltip is displayed.

**[Notes]:**
- This issue is also reproducible with the "Random" button, "generate random color" tooltip is displayed.
- This is also reproducible for the "Close" button from "Terms & Privacy" pop-up, "close" tooltip is displayed.
- Attached a screen recording of the issue:

![rec of the issue - tooltips](https://user-images.githubusercontent.com/37875464/44583485-39c28e80-a7ae-11e8-87b0-9732ef3da066.gif)

**Comment by devilsahil** [comment]
The checks have successfully passed on CircleCI. Please merge when possible. Thanks !

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible on Mac 10.13, Windows 10 x64 and Arch Linux on latest Nightly (64.0a1) with latest "Firefox Color" (1.1.0 dev version/ 12/09/2018) installed.
