### ISSUE TITLE
back button should remove image item

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/FirefoxColor#413]
now it solely removes the thumbnail, and preview color-no-background-image-button

https://github.com/mozilla/FirefoxColor/pull/391#issuecomment-416980894

**Comment by lmorchard** [comment]
Looking at this issue, I realize I don't actually understand it. What does "preview color-no-background-image-button" mean?

**Comment by johngruen** [comment]
@meandavejustice to verify and close
