### ISSUE TITLE
remove item, then back button, brings back partial item in list

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/FirefoxColor#414]
item is shown without thumbnail and preview

https://github.com/mozilla/FirefoxColor/pull/391#issuecomment-416980894

**Comment by lmorchard** [comment]
Thinking through what's going on here:

1. Remove a background, the theme is changed, so the previous state is pushed onto the undo stack.
1. The middleware notices that the image from the removed background is no longer used, [so `purgeImages` deletes it from the image store as garbage collection](https://github.com/mozilla/FirefoxColor/pull/391/files#diff-bccfe701859c09a65c2c20903446e208R80).
1. Hit the back button, and the previous theme state is popped off the undo stack and applied. However, the image used by that state is no longer available in the image store.

The theme state and image storage are separate, so maybe we need to either give the image store an undo stack or make `purgeImages` search the undo stack before garbage collecting images.
