### ISSUE TITLE
The "Toolbar Color" button wrongly overlaps the "Custom background image" string

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#436]
**[Affected versions]:**
- Firefox Nightly 64.0a1

**[Affected Platforms]:**

- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (1.1.0 custom build)
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the Firefox Color toolbar button.
3. Observe the "Custom background image" string.

**[Expected result]:**
- The "Custom background image" string is fully visible.

**[Actual results]:**
- The "Toolbar Color" button overlaps the "Custom background image" string.

 **[Notes]:**
- Attached a screenshot of the issue:

![custom background covered by toolbar color doorhanger](https://user-images.githubusercontent.com/37875464/45751720-dea08200-bc1b-11e8-9059-d54cf2f570b0.png)

**Comment by johngruen** [comment]
Closing pending merger of new UI PR
