### ISSUE TITLE
[Enhancement] Uploaded image should be displayed in the "Preview Panel"

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#437]
**[Affected versions]:**
- Firefox Nightly 64.0a1

**[Affected Platforms]:**

- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (1.1.0 custom build)
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the Firefox Color toolbar button.
3. Click the "Upload image" button and upload a valid image.
4. Observe the "Preview Panel".

**[Expected result]:**
- The uploaded image is displayed in the "Background Color" section in the "Preview Panel".

**[Actual results]:**
- The theme default in "Background Color" section in the "Preview Panel".
 
 **[Notes]:**
- Having a saved theme that contains an uploaded image has also a thumbnail without the preview of the image, making it difficult to set a theme with a specific image.
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=1130D3wQisJANlUlZdY7x8Nbl3HGr5dgq)

**Comment by johngruen** [comment]
This is half fixed in my PR, but we need to make sure images show up at smaller widths!
