### ISSUE TITLE
Error messages are not automatically dismissed

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/FirefoxColor#438]
[Affected versions]:
- Firefox Nightly, Version 64.0a1, Build ID 20180919003800

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (1.1.0 custom build installed from the "about:debugging" page).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Upload image" button and upload an invalid image (larger than 1 MB).
3. Observe the error message.

[Expected result]:
- The error message is dismissed after a few seconds. 

[Actual result]:
- The error message is not dismissed.

[Additional Notes]:
- The error message's background overlaps the buttons from the image section.
- The issue is also reproducible with the "The File is not an accepted image type." error.
- Workaround: uploading a valid image or refreshing the page will dismiss the banner.
- After uploading a large image, a circled "i" icon appears next to the "Upload image" button with the "{"tooLarge":true,"wrongType":false}" tooltip, which has no relevance to the user.
- I have attached a screen recording of the issue:
![error message](https://user-images.githubusercontent.com/40393891/45753039-2c1eee00-bc20-11e8-88d3-4fe490e04e3c.gif)

**Comment by lmorchard** [comment]
Looks like the error messages are dismissed via CSS animation with https://github.com/mozilla/FirefoxColor/commit/977e8624d86ee3af7bfb568143efec6729d656e0

But, that introduced a different issue, which PR #454 should fix.
