### ISSUE TITLE
Image titles are wrongly cut off if they are longer than 24 characters and the image has an 1:1 aspect ratio

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#439]
**[Affected versions]:**
- Firefox 62 and up

**[Affected Platforms]:**

- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (1.1.0 custom build)
installed from the "about:debugging" page.
- Have a 1:1 ratio [image](https://drive.google.com/open?id=1FQSrW83CJClabkOUk85mm5mMKjvnIqwV) with a long name.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the Firefox Color toolbar button.
3. Upload the image from the prerequisites.
4. Observe the image titles.

**[Expected result]:**
- The title of the image is shortened and has "..." at the end of it.

**[Actual results]:**
- The end of the title is cut off.

 **[Notes]:**
- This issue is also reproducible with fewer characters if the image is wider.
- Attached a screenshot of the issue:

![title of the image](https://user-images.githubusercontent.com/37875464/45759220-1fa29180-bc30-11e8-8343-318b284df088.png)

**Comment by johngruen** [comment]
So, this is related to the width of images

**Comment by johngruen** [comment]
Let's just do the image names as tooltips!

**Comment by lmorchard** [comment]
Hmm, I did stick a [`text-overflow: ellipsis`](https://github.com/mozilla/FirefoxColor/blob/master/src/web/lib/components/ThemeCustomBackgroundPicker/index.scss#L130) in there at one point. Maybe the max-width of the name field needs to be reduced a little?

**Comment by johngruen** [comment]
I think this is now fixed

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Mac 10.13, Windows 10 x64 and Arch Linux with the latest "Firefox Color" (2.0.0 dev version 10/09/2018) installed.
