### ISSUE TITLE
Gifs can wrongly be uploaded

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/FirefoxColor#440]
[Affected versions]:
- Firefox 62 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (1.1.0 custom build) installed from the "about:debugging" page.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Upload image" button and upload a gif.
3. Observe the webpage.

[Expected result]:
- The "The File is not an accepted image type." error is displayed and the gif is not uploaded.

[Actual result]:
- The gif is successfully uploaded, but the background image remains unchanged. And any changes made while a gif is uploaded are not displayed, including: changing colors, adding images, and removing images.

[Additional Notes]:
- Removing the gif causes the previous changes to update.
- I have attached a screen recording of the issue:
![gif](https://user-images.githubusercontent.com/40393891/45760631-34345900-bc33-11e8-92a6-d9655e7a77be.gif)

**Comment by johngruen** [comment]
might be related

**Comment by johngruen** [comment]
Actionable thing here is to remove gifs from the constants file

**Comment by johngruen** [comment]
Resolved in #445
