### ISSUE TITLE
All the buttons from the "Custom background image" section do not have a hover effect neither a tooltip

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#441]
**[Affected versions]:**
- Firefox 62 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (1.1.0 custom build)
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the Firefox Color toolbar button.
3. Hover the "Upload image" button from the "Custom backgroun image" section.
4. Observe the buttons behavior.

**[Expected result]:**
- The mouse changes into a hand pointer, the button gains a hover effect, and a specific tooltip is displayed.

**[Actual results]:**
- The mouse changes into a hand pointer, but the button has no hover effect and a specific tooltip is not displayed.

 **[Notes]:**
- This issue is reproducible with all the "Alignment" buttons, "Repetition" dropdown, "Replace image" button and "Delete image" button.
- Attached a screen recording of the issue:

![rec of the issue - hover and tooltips](https://user-images.githubusercontent.com/37875464/45762230-96428d80-bc36-11e8-85ec-7fd408bf439b.gif)

**Comment by johngruen** [comment]
Fixed in #445
