### ISSUE TITLE
Ensure we have decent mobile styles

### ISSUE THREAD

**Issue by lmorchard** [mozilla/FirefoxColor#45]
From [acceptance criteria](https://github.com/mozilla/ThemesRFun/blob/master/docs/acceptance.md):

> - [ ] It should have a minimal, pleasant mobile experience that lets users know it's a desktop experiment.

**Comment by youwenliang** [comment]
Here's an idea for the mobile page: (Need to think about the content)
https://mozilla.github.io/testpilot-assets/ThemesRFun/01_Measurements/Mobile_page/
Icon: https://github.com/mozilla/testpilot-assets/tree/master/ThemesRFun/01_Measurements/Mobile_page/assets

We could also add a call to action button that links to testpilot's experiment detail page.

**Comment by johngruen** [comment]
This looks good to me, i can pick this up.

**Comment by pdehaan** [comment]
@johngruen Is this still legit, or did you fix it all w/ PR #188?

**Comment by johngruen** [comment]
No we should still do something for mobile browsers
