### ISSUE TITLE
The "Custom backgrounds" elements are wrongly overlapping other areas, if more than 4 pictures are uploaded

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#450]
**[Affected versions]:**
- Firefox 62.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Color" add-on (1.1.0 custom built on 24.09.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button and select the "Custom backgrounds" tab.
3. Click the "Add your own" button and select any picture.
4. Repeat step 3 another 4 times and observe the "Custom backgrounds" area.

**[Expected result]:**
- All the elements are correctly displayed and rendered.

**[Actual result]:**
- The "Custom backgrounds" elements are wrongly overlapping other areas.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/45951336-c3fb4e00-c00b-11e8-8899-3118ba224a3b.gif)

**Comment by johngruen** [comment]
@Softvision-MariusComan this is resolved by my latest patch which limits to three uploads

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Color" add-on (1.2.0 custom built on 9/27/2018) installed. Verified on Windows 10 x64, Ubuntu 18.04.1 x64 and Mac 10.13.3 with the latest Firefox Release (62.0.2) and Firefox Nightly (64.0a1 - Build ID 20180926220146) installed.
