### ISSUE TITLE
The "Theme Textures" are not highlighted when hovered 

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#463]
**[Affected versions]:**
- Firefox 62.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Color" add-on (1.2.0 custom built on 9/27/2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Custom backgrounds" tab and hover any texture.
3. Observe the behavior.

**[Expected result]:**
- The "Themes Textures" are highlighted when hovered.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- The "Preset Themes" and the "Saved Themes" are highlighted with blue borders when hovered.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/46153547-0a56e400-c27c-11e8-807a-1f51e3d0f45a.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Mac 10.13, Windows 10 x64 and Arch Linux with the latest "Firefox Color" (2.0.0 dev version 10/09/2018) installed.
