### ISSUE TITLE
Allow users to revert to previously installed theme with Firefox Color installed

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/FirefoxColor#483]
Related to issue #302. 

It is very jarring to have a user's theme change completely upon installing Firefox Color. There should be an easy way to revert back to the last used theme, or the theme change should not happen on installation. 

cc: @atsay

**Comment by atsay** [comment]
Yes, perhaps addressing some of these cases would help improve the sense of user control. Another example is if you have Color installed but use a non-Color theme, just going to color.firefox.com results in your theme being overridden by a Color theme. Let's discuss Friday...

**Comment by lmorchard** [comment]
> if you have Color installed but use a non-Color theme, just going to color.firefox.com results in your theme being overridden by a Color theme

Yeah, that's kind of tricky. Technically, the Color add-on *is* a theme, so if you have it installed you're using *that* theme too - it'll fight with / override any other theme you've enabled. (e.g. on browser restart, Color will try to re-apply the last applied Color theme without a visit to the website)

**Comment by johngruen** [comment]
Duping this to #456
