### ISSUE TITLE
Allow users to name saved themes

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/FirefoxColor#484]
It would be helpful for designers to be able to name their saved themes, especially for prolific theme designers and testers who want to toggle back and forth between themes.

**Comment by lmorchard** [comment]
Semi-related to #195 - we have a property for "title" in the local theme schema, but not really any UX for displaying titles. Also, I thought we had an issue for naming saved themes, but I can't find it. We'd need some UX for editing those titles too

**Comment by johngruen** [comment]
Let's add this to the export modal.

Hit export button > (modal) give your theme a name > confirm > download
