### ISSUE TITLE
Implement theme-color

### ISSUE THREAD

**Issue by codythecoder** [mozilla/FirefoxColor#500]
A lot of major websites now use the [theme-color](https://developers.google.com/web/fundamentals/design-and-ux/browser-customization/#meta_theme_color_for_chrome_and_opera) tag to inform the browser what color to be. At the moment, chrome for android is the only major browser that actually uses this (that I know of), but I think that it would be something really nifty to add to firefox color.

**Is it possible?**
no idea. I've tried to figure this out, but I've never done work on addons before, so I can't tell what's possible or not. If someone who knows addons and firefox color better could tell me if it's possible or not that'd be great.

**How would it work?**
I think having a checkbox like this would work
![image](https://user-images.githubusercontent.com/13900631/46710066-16866c80-cc92-11e8-8f8c-91c971706ad7.png)
where it could be implemented on a few key groups, and then expanded out if necessary.

**Comment by johngruen** [comment]
@codythecoder this is definitely possible, but probably not on the roadmap for Firefox color. We're moving to make this a theme export tool. Recommend sticking with VivaldiFox for now.
