### ISSUE TITLE
Delete button does not bring up a confirmation dialog or an "Undo" button

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/FirefoxColor#505]
[Affected versions]:
- Firefox 62.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (2.0.0) custom built on 10/10/2018 installed.
- Have a .jpg file saved to your PC.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from the prerequisites and click the Firefox Color icon from the toolbar.
2. Click the "Custom backgrounds" button.
3. Click the "...Or add your own" button and upload a valid image to the "Custom backgrounds" section.
4. Click the "X" button from the right side of the recently uploaded image and observe the behavior.

[Expected result]:
- The image is deleted and an "Undo" button is displayed.
OR
- A confirmation dialog box is displayed.

[Actual results]:
- The image is permanently deleted.

[Notes]:
- This issue is also reproducible when deleting a saved theme.
- Attached a screen recording with the issue:

![delete](https://user-images.githubusercontent.com/26000308/46743556-03839480-ccb2-11e8-96c1-fc3a0a850412.gif)

**Comment by KhushilMistry** [comment]
Hey, I want to work on this. Do we have any mock ups for this @SoftVision-CarmenFat ?

**Comment by JanviMahajan14** [comment]
hey @caitmuenster i would like to work on this issue. Could you please guide me how to implement this.

**Comment by caitmuenster** [comment]
Hi @JanviMahajan14, sorry for the late response! This just got taken care of. :) 

We have limited resources for this project and unfortunately aren't in a good position to mentor good-first-bugs. Would you be interested in any good-first-bugs for one of Mozilla's [other projects](https://codetribute.mozilla.org/)? You can also find some good-first-bugs for our add-ons platform projects [here](https://addons-pm.herokuapp.com/contrib/good-first-bugs/?dir=desc&sort=updatedAt).

**Comment by ValentinaPC** [comment]
I have verified this issue and is no longer reproducible using the production .xpi (version 2.1.5) linked to the Stage server on Firefox Nightly (Build ID: 20200114094410), Firefox Beta 73.0b4 (Build ID: 20200112220634) and Firefox Release 72.0.1 (Build ID: 20200107212822) for Windows 10 x64, Mac 10.14.6 and Ubuntu 16.
