### ISSUE TITLE
[Windows] Running "npm install" after cloning the repo wrongly creates an invalid "vendors~." folder

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#521]
**[Affected versions]:**
- 62.0.3 and above

**[Affected Platforms]:**
- All Windows

**[Steps to reproduce]:**
1. Open the "Command Prompt" terminal.
2. Run the "git clone https://github.com/mozilla/FirefoxColor" command.
3. Run the "cd FirefoxColor" and then the "npm install" commands.
4. Run the "npm start" command. 
5. Navigate to the folder where the "Firefox Color" was installed.
6. Go to build > web folder. 
7. Open the "vendors~." file.

**[Expected result]:**
- The folder is opened and its content displayed. 

**[Actual result]:**
- "Location is not available" error is displayed. 

**[Notes]:**
- The folder also cannot be deleted because of this error. The only method to delete the folder is force removing it through "Command Prompt" terminal.
- While the build is running in the console, the following message: "95% emitting CopyPlugin"  is intermittently displayed. And the CPU usage of the "Command Prompt" terminal reaches ~80%. 
- This issue started reproducing with the custom build from 10/11/2018.
- This issue is not reproducible on Linux and Mac OSes. 
- Attached a [screen recording](https://drive.google.com/open?id=1zRh-iysThe9AWtNkz80C1x70TFep_7-x) of the issue.
- Attached a [copy of the logs](https://drive.google.com/open?id=1NHdbvyKU3aZuU88qjksitOn7nmA8EVVp) from the terminal.

**Comment by Softvision-AndreeaCupsa** [comment]
The "vendor~" folder is no longer created when running "npm start" after cloning the Firefox repo.

However while the build is running in the console on Windows 10 x64, the following message: "95% emitting CopyPlugin" is intermittently displayed. And the CPU usage of the "Command Prompt" terminal reaches ~80%, thus slowing down the PC. 

On Mac 10.13.3 while the server for the add-on is running, node reaches ~ 100% usage of the CPU.
 
On Linux, the following message "92% after chunk asset optimization SourceMapDevToolPlugin contentScript.js gene" is displayed after each appearance of the "95% emitting CopyPlugin" message. CPU usage on Linux is only ~15%. 

This issue is not reproducible if I clone the stage branch, build it and run it. CPU usage sits at around ~10-20% with the stage clone. 

Considering this I will reopen this issue.

**Comment by lmorchard** [comment]
Is this CPU usage thing directly related to the change in vendors folder name? Sounds like it might be a different issue

**Comment by Softvision-AndreeaCupsa** [comment]
It might not be related to it, we noticed them at the same time. I will log another issue for high CPU usage.

**Comment by johngruen** [comment]
@lmorchard can you verify this is fixed and close

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Windows 10x 64 with the latest custom build (11/02/2018).
