### ISSUE TITLE
High CPU usage of the terminal while running "npm start" after cloning the master branch

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#529]
**[Affected Platforms]:**
- All Windows
- All Mac

**[Steps to reproduce]:**
1. Open the "Command Prompt" terminal.
2. Run the "git clone https://github.com/mozilla/FirefoxColor" command.
3. Run the "cd FirefoxColor" and then the "npm install" commands.
4. Run the "npm start" command.
5. Open the "Task Manager" and observe the CPU usage of the "Command Prompt" terminal.

**[Expected result]:**
- The CPU usage is in normal parameters. 

**[Actual result]:**
- The CPU usage reaches ~80%.

**[Notes]:**
- Also on Windows the following message "95% emitting CopyPlugin" is intermittently displayed.
- This issue is not reproducible if I clone the stage branch, build it and run it. CPU usage sits at around ~10-20% with the stage clone.
- On Mac 10.13.3 while the server for the add-on is running, node reaches ~ 100% usage of the CPU.
- On Linux, the following message "92% after chunk asset optimization SourceMapDevToolPlugin contentScript.js gene" is displayed after each appearance of the "95% emitting CopyPlugin" message. CPU usage on Linux is only ~15%.
- Attached a screen recording of the issue:

![rec of the issue - high cpu usage](https://user-images.githubusercontent.com/37875464/47228441-e6e00e80-d3cd-11e8-806b-43252e5944c3.gif)

**Comment by johngruen** [comment]
@lmorchard will look, but probably stetch

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest custom build (11/12/2018) from the Github Repo on Windows 10 x64 and Mac 10.13.3.
