### ISSUE TITLE
Continuous deployment to gh-pages from master?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/FirefoxColor#53]
In #7, I got auto-deployment to gh-pages working from the development branch - not master. That means any deploy to dev has to go through that branch first. This differs from Test Pilot proper.

Apropos of that difference, it might be nice to make every merge to master get deployed. 

This is practically blocked by #21 - since there will be an error in add-on signing during deployment unless the add-on version is changed on every commit.

**Comment by pdehaan** [comment]
I think I have a related question... Are we planning on having a webserver for this service? As far as I can tell, we're currently using some single page React app on mozilla.github.io/ThemesRFun.

But should we be standing up some Express/Hapi server to serve the page+assets and stuff like a `/__version__` endpoint and other OPs like endpoints for health checks, etc?

**Comment by meandavejustice** [comment]
@pdehaan This may be a dumb question, but couldn't we still serve the `__version__` endpoint and health checks from ghpages? Seems like they could just be statically served json files generated at build/deploy time.

Additionally, I wonder if there are any existing user facing mozilla sites hosted on gh-pages. if so there might be something internally that could check status.github.com.

**Comment by pdehaan** [comment]
I'm sure we could we could serve a static ghpages of `/__version__`. I was just thinking if OPs is going to be deploying a server for production, it'd make sense for dev/stage to follow similar processes/infra so we could verify server deployments.

Here's what the [testpilot.firefox.com](https://testpilot.firefox.com/__version__) looks like:

```json
{
  "commit": "3cfbd582b52caaf0b4c032d15b5d886a7827ec31",
  "version": "2018-02-06",
  "source": "https://github.com/mozilla/testpilot"
}
```

... or [send.firefox.com's `/__version__`](https://send.firefox.com/__version__) endpoint:

```json
{
  "commit": "82fe65a",
  "source": "https://github.com/mozilla/send/",
  "version":"v2.3.1"
}
```

So as long as we can rewrite a static `/__version__` file with the current Git SHA, and package.json `version` number, and the static `source` field which will never change.

Depending on whether we touch any other services, we could probably just return 200/OK responses for the `/__heartbeat__` and `/__lbheartbeat__` OPs endpoints as well.

I think my main thinking right now, is I was filing bugs against the current ghpages deployment, but wasn't sure if the code is an hour/day/week old.

**Comment by lmorchard** [comment]
> I think I have a related question... Are we planning on having a webserver for this service?

Yes, though it might just be Amazon S3, in production.

> As far as I can tell, we're currently using some single page React app on mozilla.github.io/ThemesRFun.

Yes, that's how it's served up in development right now. We're not planning to use GitHub Pages in production.

> But should we be standing up some Express/Hapi server to serve the page+assets and stuff like a /__version__ endpoint and other OPs like endpoints for health checks, etc?

We don't need that - hosting would be similar to Test Pilot, which also lives on Amazon S3. The /__version__ endpoint is just a static file.

**Comment by lmorchard** [comment]
> I was just thinking if OPs is going to be deploying a server for production, it'd make sense for dev/stage to follow similar processes/infra so we could verify server deployments.

Also, FWIW: On Test Pilot itself, the development site is self-service by the dev team. Stage & prod are managed by ops. All basically S3 + CloudFront, but dev uses public CircleCI while stage & prod use internal Jenkins.

**Comment by lmorchard** [comment]
> I think my main thinking right now, is I was filing bugs against the current ghpages deployment, but wasn't sure if the code is an hour/day/week old.

And also FWIW: gh-pages deployment is currently a manual push to the development branch - it doesn't track master. Thus, this issue to change that to continuous deployment.

**Comment by lmorchard** [comment]
Files [an issue](https://github.com/mozilla/ThemesRFun/issues/60) to remember to actually  generate a `/__version__` resource

**Comment by lmorchard** [comment]
We probably don't really need to solve this.
