### ISSUE TITLE
The uploaded images that have the ".BMP" format are not applied to the theme background

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#547]
**[Affected versions]:**
- Firefox 63.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (2.1.0) installed from "mozilla.github.io/FirefoxColor".
- Have an image with the".BMP" format and up to 1MB saved to your drive.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button and select the "Custom backgrounds" tab.
3. Click the "...Or add your own" button and select the image from prerequisites.
4. Observe the behavior

**[Expected result]:**
- The image is applied to the theme background and also to the preview panel.

**[Actual result]:**
- The image is applied only to the preview panel.

**[Notes]:**
- The issue persists even if you will add images with other formats (JPG or PNG) after the ".BNP" image type is added and is no longer reproducible after it is deleted.
- This issue is also reproducible with the TxP version of the "Firefox Color" add-on.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/47854455-6f0cdd80-ddea-11e8-8119-aade69e00ea4.gif)

**Comment by lmorchard** [comment]
Hmm, this might be a type that's not supported / has broken support in the upstream theme APIs in Firefox. If so, we might have to remove .bmp from the list of allowed media types.

**Comment by lmorchard** [comment]
Just going to disable this media type for now

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Firefox Color custom build (11/15/2018) on Windows 10 x64, Mac 10.13.3 and Arch Linux.
