### ISSUE TITLE
when using color.firefox.com form input elemants are affected, but not configurable

### ISSUE THREAD

**Issue by ratron** [mozilla/FirefoxColor#590]
eg: the background color applies to all unstyled form elements on webbages. the browser default is white (text) or gray (radio,checkbox). color.firefox.com messes up the browser defaults but does not offer a configuration for those elements.

**Comment by johngruen** [comment]
@ratron can you provide a URL where you are seeing this and maybe a screenshot? Additionally do you have high contrast mode enabled on an OS level?

**Comment by ratron** [comment]
i'm so sorry, it was the theme. i changed firefox colors and theme at the same time, but the theme did not affect chromium - so i thought it was caused by firefox color.

![image](https://user-images.githubusercontent.com/14057805/49137180-fa936480-f2eb-11e8-8cc8-7dd1359df8d0.png)
