### ISSUE TITLE
Generate /__version__ resource on deployment

### ISSUE THREAD

**Issue by lmorchard** [mozilla/FirefoxColor#60]
We should have a `/__version__` resource like Test Pilot that gets generated on deployment. Properties something like this:
```json
{
  "commit": "3cfbd582b52caaf0b4c032d15b5d886a7827ec31",
  "version": "2018-02-06",
  "source": "https://github.com/mozilla/ThemesRFun"
}
```

**Comment by pdehaan** [comment]
Not sure if we want `/__heartbeat__` and `/__lbheartbeat__` endpoints too, per https://mana.mozilla.org/wiki/display/SVCOPS/New+Service+Guide#NewServiceGuide-StandardEndpoints

It may depend on whether we're hosting this ourselves, or if OPs will be hosting it.

**Comment by lmorchard** [comment]
We don't have those for Test Pilot, so we probably won't have them here. I think those endpoints are mainly for where there's a web application server. The heartbeat is for the app server and lbheartbeat is for a load balancer, and we'll have neither.

**Comment by apoorvasingh17** [comment]
@lmorchard Hello, I am new here and would like to contribute to this issue. Can I take this up?

**Comment by meandavejustice** [comment]
Hey @apoorvasingh17, to get started take a look at https://testpilot.firefox.com/__version__, that's the format we'll need to generate

**Comment by Meikay** [comment]
Hi @lmorchard, I am a new contributor and part of the outreachy internship. Where can I get started contributing to this project as a newcomer?

**Comment by pdehaan** [comment]
@Meikay,

Welcome! The best place to start is probably the [CONTRIBUTING.md](https://github.com/mozilla/Themer/blob/master/CONTRIBUTING.md) page in this repo. It has some good instructions and a link to some [good first issues](https://github.com/mozilla/Themer/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).
