### ISSUE TITLE
Sidebar theming

### ISSUE THREAD

**Issue by happysurf** [mozilla/FirefoxColor#616]
Please add the sidebar theming support like in the default dark Firefox theme.
Now with the API is possible.
For example, if I added in Firefox Color exported manifest.json file this code, then works:

      "sidebar":` "#404552", // Firefox 63
      "sidebar_text": "#D3DAE3", // Firefox 63
      "sidebar_border": "#2B2E39", // Firefox 64
      "sidebar_highlight": "#5294E2", // Firefox 63
      "sidebar_highlight_text": "#E3EAF3" // Firefox 63

**Comment by MichaelTunnell** [comment]
This would be great! I use dark themes on applications and the super bright sidebar is rather annoying. Of course, not annoying enough to not use Firefox but it would be fantastic if I could style that with this extension as well.

**Comment by andreicristianpetcu** [comment]
will be editable once this lands https://github.com/mozilla/FirefoxColor/issues/923#issuecomment-626269298
