### ISSUE TITLE
What is the plan for Firefox Color after Test Pilot is Deprecated?

### ISSUE THREAD

**Issue by MichaelTunnell** [mozilla/FirefoxColor#667]
Announcement to end Test Pilot:
https://blog.mozilla.org/blog/2019/01/15/evolving-firefoxs-culture-of-experimentation-a-thank-you-from-the-test-pilot-program/

I am wondering what is the plan for Firefox Color? Will Firefox Color be turned into an independent extension or will it be ended alongside Test Pilot?

Note: personally speaking, Firefox Color is the only extension that I would miss from the current set of Test Pilot experiments. I have used so many Test Pilot things over the years especially Containers and since those have all graduated, the only one left for me is Firefox Color so :crossed_fingers:

**Comment by marniepw** [comment]
@MichaelTunnell have no fear. Color is a popular experiment and will live on in AMO.
