### ISSUE TITLE
Start page white backgrund

### ISSUE THREAD

**Issue by zynexiz** [mozilla/FirefoxColor#740]
The background on the start page doesn't honor the built in dark theme when it's active, seems like it revert to the light theme when the addon is activated. Also found this issue with firefox-nativedark addon. Maybe a Firefox issue more than an addon issue?

![Screenshot_20190313_135157](https://user-images.githubusercontent.com/22789493/54280200-d1db6600-458e-11e9-9b9c-1a7315455d47.png)

**Comment by harogaston** [comment]
Please, this issue is keeping me from using the extension at all. I can't go with a bright flash in my eyes every time I open a new tab.

**Comment by dcormier** [comment]
I think this is no longer the case. With the built-in dark theme active, the default tab page has a black background.

**Comment by harogaston** [comment]
> With the built-in dark theme active, the default tab page has a black background.

 Only as long as you don't enable Firefox Color. Exactly the reason why this is still an issue.

**Comment by zynexiz** [comment]
> > Also found this issue with firefox-nativedark addon. Maybe a Firefox issue more than an addon issue?
> 
> I think this is no longer the case. With the built-in dark theme active, the default tab page has a black background.

This is still the case. I have both dark theme and this plugin active. Front page is still white.

**Comment by jtagcat** [comment]
Related: https://support.mozilla.org/en-US/questions/1279034

**Comment by andreicristianpetcu** [comment]
Will be fixed by this https://github.com/mozilla/FirefoxColor/issues/923#issuecomment-626269298

**Comment by andreicristianpetcu** [comment]
Check out the new tab color in the advanced tab.

**Comment by Rob--W** [comment]
This has been resolved by #940 thanks to @andreicristianpetcu .
