### ISSUE TITLE
Update properties that will be deprecated in Firefox 69

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/FirefoxColor#763]
In [Firefox 69](https://wiki.mozilla.org/Release_Management/Calendar), the following theme properties will be deprecated: 

- toolbar_text
- accentcolor
-textcolor

[MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#Aliases) recommends replacing themes with the following: 

-bookmark_text
-frame
-frame_inactive
-tab_background_text

We need to replace the deprecated properties with the recommended replacements prior to Firefox 69 going into the Beta channel (July 9, 2019).

**Comment by caitmuenster** [comment]
@ntim made some corrections to the properties set to be deprecated: 

- For `accentcolor`, please use `frame`
- For `headerURL`, please use `theme_frame`
- For `textcolor`, please use `tab_background_text`

`toolbar_text` is no longer going to be deprecated.

**Comment by gaby2300** [comment]
So, when this issue is fixed, will the inactive/background color issue in Firefox Color be fixed as well?

**Comment by caitmuenster** [comment]
@gaby2300 Correct! The properties behind inactive/background color were deprecated and will be removed from Firefox 70.

**Comment by gaby2300** [comment]
@caitmuenster Do you know when will this happen in Nightly?

**Comment by caitmuenster** [comment]
@gaby2300 Hopefully soon -- there's a patch in progress. If you want to subscribe to this issue, you'll be notified when it's been fixed. :)

**Comment by gaby2300** [comment]
@caitmuenster By subscribe to this issue, do you mean to watch it?

**Comment by IdmFoundInHim** [comment]
> 
> 
> @caitmuenster By subscribe to this issue, do you mean to watch it?

In the notifications section (right side of the screen on desktop or bottom of the page on mobile), there is a subscribe button. When you click it, you are subscribed and will receive notifications for new activity on just this issue. To unsubscribe, click the button again (which will say unsubscribe, as it does for me).
Before:
![image](https://user-images.githubusercontent.com/30935172/62643470-08d35f00-b916-11e9-8708-4fe8f0738029.png)
After:
![image](https://user-images.githubusercontent.com/30935172/62643285-9d898d00-b915-11e9-9c2b-fc9dd7f05b81.png)

**Comment by gaby2300** [comment]
@IdmFoundInHim Subscribed! Thank you so much for such a detailed explanation!

**Comment by caitmuenster** [comment]
Hey @gaby2300, we just updated the extension and site. Could you check to see if it's working for you now?

**Comment by gaby2300** [comment]
Hello @caitmuenster, I'm so sorry for my delay!
It seems I didn't receive this last update, that's why I didn't answer before. I just happened to check this issue and noticed the update!
Yes, it's working fine now, thanks!
