### ISSUE TITLE
Remove Test Pilot references from website

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/FirefoxColor#783]
We also need to remove references to Test Pilot from the website: 

![Test Pilot - Color](https://user-images.githubusercontent.com/23342476/56147478-33f80400-5f5d-11e9-86e6-c085ba3bd5b0.png)

**Upper left corner:** 
- Remove "A Firefox Test Pilot experiment"
- Center "Firefox Color" with icon 

**Footer:**
- Remove "About Test Pilot" link
- Change link target of Twitter icon to https://twitter.com/firefox/

**Comment by psanatov** [comment]
I'm not sure that logo is centered in a correct way. @caitmuenster what do you think?
![Screenshot from 2019-04-18 09-46-37](https://user-images.githubusercontent.com/33035511/56344951-eaa6ef00-61be-11e9-8fba-fe74aa9be001.png)

While I was trying to fix this ticket, I thought that we should center logo **against parent** (whole header element), not just left part of the header.

**Comment by caitmuenster** [comment]
Thanks @psanatov! Oh, yeah -- I'd like to keep its original position on the left hand side. Sorry for the confusion; I meant that the words "Firefox Color" should be centered against the icon. :) 

@mgillespy, do you want to make that quick fix and re-submit the PR?
