### ISSUE TITLE
Update for Firefox 69?

### ISSUE THREAD

**Issue by happysurf** [mozilla/FirefoxColor#798]
With my theme Solarize Fox (https://addons.mozilla.org/en-US/firefox/addon/solarize-fox/) created and exported with FirefoxColor  2.1.0 addon, I get this error in debug mode:

Solarize Fox:
    Reading manifest: Error processing theme.colors.accentcolor: Please use <em>theme.colors.frame</em>, this alias will be removed in Firefox 69.
    Reading manifest: Error processing theme.colors.textcolor: Please use <em>theme.colors.tab_background_text</em>, this alias will be removed in Firefox 69.
    Reading manifest: Error processing theme.colors.toolbar_text: Please use <em>theme.colors.bookmark_text</em>, this alias will be removed in Firefox 69.

**Comment by caitmuenster** [comment]
Thanks @happysurf! We're working on a fix for this. 

Do you know how to edit the manifest.json of your theme? You can swap out the properties, rezip the file, and then sideload it to fix the error.

**Comment by happysurf** [comment]
> 
> 
> Thanks @happysurf! We're working on a fix for this.
> 
> Do you know how to edit the manifest.json of your theme? You can swap out the properties, rezip the file, and then sideload it to fix the error.

Yes, this morning I have updated the theme (queue), but my questions are:
- The updated theme works also with Firefox 57 and 58 versions?
- These 59 changes (and others?) allow more customize UI colors for Firefox 59+ ?

**Comment by caitmuenster** [comment]
This should have been fixed with #826.
