### ISSUE TITLE
Fix stage & production deployment

### ISSUE THREAD

**Issue by jbuck** [mozilla/FirefoxColor#802]
We're now [deploying via CircleCI](https://github.com/mozilla/FirefoxColor/pull/797) but there are still some bugs to be ironed out.

The first thing I noticed [on stage](https://color.stage.mozaws.net/) is that it's trying to install the XPI from stage, rather than referring to testpilot.firefox.com. I looked at the build config and the following two things needs to be changed:

* Stage
  * ADDON_URL=https://testpilot.firefox.com/files/FirefoxColor-stage@mozilla.com/signed-addon.xpi
  * SITE_URL=https://color.stage.mozaws.net/
* Prod: 
  * ADDON_URL=https://testpilot.firefox.com/files/FirefoxColor@mozilla.com/signed-addon.xpi
  * SITE_URL=https://color.firefox.com/

Then run `npm run build:web` and `aws s3 sync` as we already do

**Comment by caitmuenster** [comment]
Pending verification that we can push to prod, I think we can close this out. 

We do need to have the .xpi hosted on AMO so users don't see the pop-up asking if they trust Firefox to download from a non-AMO site (see issue #812).

**Comment by Rob--W** [comment]
The xpi link now points to AMO, and the xpi deployment process has been updated and documented:
https://github.com/mozilla/FirefoxColor/blob/444d50d1dc12fb20b52029000bdb9cb74148692c/README.md#build-test-and-publish-add-on
