### ISSUE TITLE
Share (export) current theme

### ISSUE THREAD

**Issue by Eccenux** [mozilla/FirefoxColor#804]
There seem to be no way to export current theme. For example I did some theme a year ago or so and now I cannot event share it between my own computers.

There should be a way to generate the link from options or export (and import) some JSON.

**Comment by GeekBoySupreme** [comment]
To implement this, we would have to go through and change the fundamentals in which the theme colors are ingested.
Is anyone working on this?
I would love to help out here.

**Comment by Rob--W** [comment]
There is already an export button to export as extension. There is also a Share button to generate a link to share themes.

Because the requested features are already available, I'll close this issue.
If you still feel that something is missing, let me know and I'll reconsider.
