### ISSUE TITLE
Upgrade to node 10

### ISSUE THREAD

**Issue by wagnerand** [mozilla/FirefoxColor#820]
This project is currently using node 8, which reaches its end of life in December 2019. We need to upgrade to at least node 10 before that.

**Comment by Patil2099** [comment]
@wagnerand Can I work on this?

**Comment by caitmuenster** [comment]
Hey @Prankaj, thanks for your interest in this bug! Unfortunately, this is not a good bug for contributors. Would you be interested in working on other issues for Mozilla projects? The DevTools group in particular have a lot of [good issues](https://codetribute.mozilla.org/projects/devtools) to dive into. :)
