### ISSUE TITLE
production site is not pointing at AMO addon

### ISSUE THREAD

**Issue by jbuck** [mozilla/FirefoxColor#828]
Right now the production site is pointing at the Testpilot-hosted addon and not the AMO-hosted addon. I'm not sure why, the code is exactly the same as stage which is pointing at the AMO-hosted addon

**Comment by Rob--W** [comment]
https://github.com/mozilla/FirefoxColor/blob/67dce659f3c508a61fbc7759e6932606304d0317/package.json#L46

should include `--channel=listed`, or (preferably) the `WEB_EXT_CHANNEL=listed` environment variable should be set in the deploy-to-production CI task.

**Comment by jbuck** [comment]
This is because I goofed and did not disable the Jenkins deployment automation, which overwrote the website/xpi on every deploy
