### ISSUE TITLE
FF 70b1 background image is missing

### ISSUE THREAD

**Issue by Draghmar** [mozilla/FirefoxColor#836]
Hi.
My FF updated to 70b1 and first thing I've noticed is that the background image isn't there any more. It wasn't custom one but one of the available at the editor. Looking at other backgrounds I think there's something wrong with alpha because some the images are visible but not in the intended way I think.
When choosing random presets there is also no background at inactive tabs.

**Comment by Rob--W** [comment]
What version of Firefox Color are you using? (the latest version is 2.1.5)
 Could you share the theme that you're using?

To be able to reproduce your exact theme, could you take the following steps:

1. Visit `about:debugging` . Click on the "This Nightly" link in the first paragraph.
2. Scroll to "Firefox Color" and click Inspect
3. Click on "Console", and paste the following code:

    ```javascript
    JSON.stringify(await browser.storage.local.get())
    ```
4. Copy the result and paste it here (wrap the line in backticks (`) to avoid formatting).

**Comment by Draghmar** [comment]
Yeah...that's kinda lame of me but I was using this addon for so long I forgot it wasn't direct part of the FF itself and...it didn't update right away for some reason. I had 2.1.2 and updating to 2.1.5 fixed this issue.
Sorry for bothering you. :(
