### ISSUE TITLE
Update installation flow & first run

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/FirefoxColor#841]
## Installation flow from web property
When users install Firefox Color from the web property, they see this warning: 

![Screen Shot 2019-09-19 at 4 16 31 PM](https://user-images.githubusercontent.com/23342476/65287671-df9f1480-daf8-11e9-8370-fb38fc376132.png)

The only way to avoid that warning is to have users install the extension from the Firefox Color product page on AMO (https://addons.mozilla.org/firefox/addon/firefox-color/). 

### Send web users who don't have the extension installed to AMO to install 

- Users who start from color.firefox.com should be directed to the AMO product page when they click the green button that says "Install Firefox Color." 

- Let's change the button text to say "Get Firefox Color". 

## First run of Firefox Color extension for everyone 

- Once a user has installed the extension from AMO, the extension should pop open a new tab that goes to color.firefox.com and runs the modal onboarding flow.

**Comment by tharun208** [comment]
I like to work on this

**Comment by caitmuenster** [comment]
Thanks for your interest, @tharun208! Rebecca is currently working on this issue. 

Would you be interested in looking at [good-first-issues](https://codetribute.mozilla.org/) for other Mozilla projects?

**Comment by tharun208** [comment]
Yes, I am
