### ISSUE TITLE
Address bar is transparent when Firefox Color is enabled

### ISSUE THREAD

**Issue by Errolyn** [mozilla/FirefoxColor#843]
In the recent release of Firefox Nightly introducing the mega bar (71.0a1), when the Firefox Color add on is enabled the address bar search drop down becomes unreadable. The bug in bugzilla can be found: https://bugzilla.mozilla.org/show_bug.cgi?id=1586054

Cross posting for visibility.

**Comment by caitmuenster** [comment]
Thanks for the heads up, @Errolyn! :) We'll keep our eyes on this in bug 1586054. I don't think the mega bar should be using the value of the URL bar. If the mega bar becomes its own customizable property, we'll see if we can add it to Color.
