### ISSUE TITLE
Images used in saved themes are wrongly removed after they are deleted from the “Custom backgrounds” section

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#847]
**[Affected versions]:**
- Firefox Nightly 71.0a1, Build ID: 20191013213650
- Firefox Beta 70.0b14, Build ID:20191013213650
- Firefox Release 69.0.3, Build ID: 20191009172106

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox Color add-on zip modified in order to link to the [stage](https://color.stage.mozaws.net/) website.
- Have the previous Firefox Color add-on installed through about:debugging.

**[Steps to reproduce]:**
1. Open the profile from the prerequisites.
2. Navigate to the https://color.stage.mozaws.net/ website.
3. Click the “Custom backgrounds” section and add a valid image.
4. Click on the “Save” button from the top toolbar.
5. Click the “Custom backgrounds” section and delete the previously added image.
6. Click the “Saved themes” section and observe the displayed theme.
7. Observe the displayed local storage info.

**[Expected result]:**
Step 6. The theme is correctly displayed and contains the added image. 
Step 7. The size of the image is correctly displayed by the local storage info. 

**[Actual result]:**
Step 6. The theme no longer contains the added image.
Step 7. The local storage info displays that only 0.001 MB is being occupied.

**[Notes]:**
- This issue is not reproducible on the [production](https://send.firefox.com) website.
- Attached a screen recording with the issue:
![Image from the saved theme is deleted](https://user-images.githubusercontent.com/37875464/66748129-19143700-ee8f-11e9-8383-78f530e23ee1.gif)

**Comment by rebmullin** [comment]
hi @Softvision-AndreeaCupsa, thanks for the feedback:) So when the image is removed as you show above, it is known that it will no longer be available to the theme. @caitmuenster can confirm this but I think the hope is that the user will export their theme before deleting the image (also there is an upcoming feature which will hopefully address some of this I believe). 
Also, removing the image also will impact the local storage value (since that image takes up space) so this looks right to me.

**Comment by Softvision-AndreeaCupsa** [comment]
Thanks, @rebmullin , that seems understandable. However, as this behavior is not reproducible on the current production website, for a user that was used with deleting an image and it not being also deleted from a saved theme, it might seem like data loss. 
In this case, we would recommend to at least notify the users that the image will also be removed from saved themes and ask if they want to proceed or not.

Considering this I will close this issue and mark it as wontfix. I have opened #852 to track the addition of a notification for users.
