### ISSUE TITLE
Images not used in saved/set themes are not cleared from the local storage space after closing a tab session

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#849]
**[Affected versions]:**
- Firefox Nightly 71.0a1, Build ID: 20191013213650
- Firefox Beta 70.0b14, Build ID:20191013213650
- Firefox Release 69.0.3, Build ID: 20191009172106

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox Color add-on zip modified in order to link to the [stage](https://color.stage.mozaws.net/) website.
- Have the previous Firefox Color add-on installed through about:debugging.

**[Steps to reproduce]:**
1. Open the profile from the prerequisites.
2. Navigate to the https://color.stage.mozaws.net/ website.
3. Click the “Custom backgrounds” section and add a valid image.
4. Click the “Random” button.
5. Close the tab.
6. Open a new tab and navigate to the https://color.stage.mozaws.net/ website.
7. Observe the local storage space.

**[Expected result]:**
- The local storage is cleared and 0MB is occupied.

**[Actual result]:**
- The local storage is not cleared and the size of the previously added image is displayed.

**[Notes]:**
- A user might easily reach the maximum limit of the local storage space if the local storage is not cleared of the added images from history after closing a tab session (images from used/saved themes must remain in storage). 
-  As a user is no longer able to navigate through history on a new session in order to delete images added in a previous session it might make it impossible to add more images.
- Due to the fact that the add-on was installed as a temporary add-on (through about:debugging) I was not able to test the scenarios including restart.
- Attached a screen recording with the issue.
![Local storage](https://user-images.githubusercontent.com/37875464/66759384-d52e2b80-eea8-11e9-85d0-700329ac2970.gif)

**Comment by rebmullin** [comment]
hmm @Softvision-AndreeaCupsa, yes typically you can remove the image from local storage if its saved to a theme but I see in this case that's not done so just thinking @caitmuenster, maybe we can remove any images from local storage is there is no theme.?

**Comment by caitmuenster** [comment]
@rebmullin That makes sense to me!

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible using the production xpi (version 2.1.5) linked to the stage server on Firefox Release 72.0.1 on Windows 10 x64, Mac 10.14.6 and Ubuntu 18.
