### ISSUE TITLE
Images used in saved/set themes are wrongly deleted when going over the maximum limit

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#850]
**[Affected versions]:**
- Firefox Nightly 71.0a1, Build ID: 20191013213650
- Firefox Beta 70.0b14, Build ID:20191013213650
- Firefox Release 69.0.3, Build ID: 20191009172106

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox Color add-on zip modified in order to link to the [stage](https://color.stage.mozaws.net/) website.
- Have the previous Firefox Color add-on installed through about:debugging.
- Have saved themes with images until the “You have almost reached your storage limit! You may need to delete some images or themes to make space”.

**[Steps to reproduce]:**
1. Open the profile from the prerequisites.
2. Navigate to the https://color.stage.mozaws.net/ website.
3. Click the “Custom backgrounds” section.
4. Add an image with a higher size in order to go over the maximum limit.
5. Navigate to the “Saved themes” section and observe the section.

**[Expected result]:**
- All images are deleted from the saved themes.

**[Actual result]:**
- The saved themes are correctly displayed with the added images.

**[Notes]:**
- After overreaching the maximum local storage size all previously added images are deleted from the local storage. Depending on the size of the last image added it might be added or not to the local storage.
- Attached a screen recording with the issue [here](https://drive.google.com/open?id=1_VDAX17Tve3zrtLW1lJ90DfsXliIbUQo).

**Comment by rebmullin** [comment]
thanks so much for the feedback. I will investigate..

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible using the production xpi (version 2.1.5) linked to the stage server on Firefox Release 72.0.1 on Windows 10 x64, Mac 10.14.6 and Ubuntu 18.
