### ISSUE TITLE
The user is not informed that deleting an image used in a saved theme will also be deleted from the saved theme

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#852]
**[Notes]:**
- As this issue is not reproducible on the [production website](https://color.firefox.com) and existing users are already used that deleting an image used in saved themes from the “Custom backgrounds” section will not delete the image from the saved themes, this new behavior might seem like data loss. 
- By informing the users that there is a new behavior when deleting an image used in saved themes and asking for confirmation in order to proceed with deleting the image might avoid any confusion. 

**[Affected versions]:**
- Firefox Nightly 71.0a1, Build ID: 20191013213650
- Firefox Beta 70.0b14, Build ID:20191013213650
- Firefox Release 69.0.3, Build ID: 20191009172106

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox Color add-on zip modified in order to link to the [stage](https://color.stage.mozaws.net/) website.
- Have the previous Firefox Color add-on installed through about:debugging.
- Have a saved theme containing an image.

**[Steps to reproduce]:**
1. Open the profile from the prerequisites.
2. Navigate to the https://color.stage.mozaws.net/ website.
3. Select the saved theme and go to the “Custom backgrounds” section.
4. Click the “Delete” button from the image.
5. Observe the behavior.

**[Expected result]:**
- A modal is displayed informing the user that deleting the image will also delete it from the saved theme and asking the user for permission in order to proceed.

**[Actual result]:**
- The image is deleted.

**Comment by caitmuenster** [comment]
One option would be to open a little dialogue box the first time a user clicks the "X" for delete. The dialogue would say, "Deleting this image will remove it from any saved themes you have. Do you want to proceed? [OK (in a blue box)]" 

Or maybe we could add a little [notification button](https://design.firefox.com/icons/viewer/#s) (from the Photon style guide) next to the "X" and have the text show up when the user hovers over the button or if they click the button (like with the Share button; screenshot below): 

![Screen Shot 2019-10-18 at 4 21 12 PM](https://user-images.githubusercontent.com/23342476/67133791-5ea06f00-f1c3-11e9-8c07-f57278f51ccf.png)

Not sure how difficult it is to implement the drop-down notification vs the hovertext; interested in hearing your thoughts, @rebmullin!

**Comment by rebmullin** [comment]
hey @caitmuenster :) So if you did want to go the notification icon route, would you want it to look like something like either of these:

<img src="https://monosnap.com/image/d4vylMZ6kZsc14kCIw1hgSqrZ2t5al.png" width="200"/>

OR

<img src="https://monosnap.com/image/sf9NEUEKnvPIPV7VnRh6nASNI4IrRC.png" width="200" />

I think the notification might be a little easier to implement but I'm thinking the first method might make a little bit more sense imo. But I'm wondering if it should only be the first time.?

**Comment by caitmuenster** [comment]
Just chatted with @rebmullin -- we're dropping the notification icon. The first time a user clicks the "X", they'll get the notification. Once they accept, they will need to click the "X" again to delete the image. They won't get the notification for following "X"s.

**Comment by rebmullin** [comment]
adding some extra notes here: 

- this is the "sketch" that I got approval on:
https://monosnap.com/file/hFXIlr3y227xDKSVGYmWH5kiTHSjmg 

- clicking either "okay" or "cancel" will prevent this modal from being seen again in the session

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible using the production xpi (version 2.1.5) linked to the stage server on Firefox Release 72.0.1 on Windows 10 x64, Mac 10.14.6 and Ubuntu 18.
