### ISSUE TITLE
A blank custom background item is wrongly displayed after pressing the “Undo” button if an image was previously deleted

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#853]
**[Affected versions]:**
- Firefox Nightly 71.0a1, Build ID: 20191013213650
- Firefox Beta 70.0b14, Build ID:20191013213650
- Firefox Release 69.0.3, Build ID: 20191009172106

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox Color add-on zip modified in order to link to the [stage](https://color.stage.mozaws.net/) website.
- Have the previous Firefox Color add-on installed through about:debugging.

**[Steps to reproduce]:**
1. Open the profile from the prerequisites.
2. Navigate to the https://color.stage.mozaws.net/ website.
3. Click the “Custom backgrounds” section and add a valid image.
4. Click the “Delete” button from the image.
5. Click the “Undo” button from the top toolbar.
6. Observe the “Custom backgrounds” section.

**[Expected result]:**
- The section of the previously deleted image is not displayed.

**[Actual result]:**
- The image background section is displayed but it does not contain an image.

**[Notes]:**
- This issue is not reproducible on the [production website](https://color.firefox.com). Here the image background section is correctly displayed with all its elements.
- Attached a screen recording with the issue: 
![Delete image](https://user-images.githubusercontent.com/37875464/66832165-00c11c80-ef62-11e9-93ab-cba6577618d7.gif)

**Comment by caitmuenster** [comment]
Thanks, @Softvision-AndreeaCupsa! @rebmullin, is it ok if I ask you to take a look at this?

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible using the production xpi (version 2.1.5) linked to the stage server on Firefox Release 72.0.1 (Build ID:20200107212822), Firefox Beta 73.0b2 (Build ID: 	20200107212705) and Firefox Nightly (Build ID: on Windows 10 x64, Mac 10.14.6 and Ubuntu 18.
