### ISSUE TITLE
Firefox 70 Breaks Firefox Color Custom backgrounds

### ISSUE THREAD

**Issue by LarnuUK** [mozilla/FirefoxColor#869]
This is a post I made on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1590646), but was closed as a duplicate, saying that Firefox 70 deprecated Firefox color. This seems very unlikely, considering that if it was, then the add on should no longer be shipped with Firefox 70 (which it is).

On Windows (1903 when I made the post, but now 1910), the top area is white, missing the background colour:
![image](https://user-images.githubusercontent.com/20837086/69572245-a208ad00-0fbb-11ea-8e5c-a140af550997.png)

I doubt that this is an API issue, due to the fact that I can only replicate the issue on one computer (the Windows instance at work). Firefox Color works fine on both Kubuntu (19.10) and my home Windows Installation; as seen below:

![image](https://user-images.githubusercontent.com/20837086/69572327-d4b2a580-0fbb-11ea-863b-612f845660b9.png)

I'm therefore raising a issue here instead, in the hope it'll be address rather than ignored.

Not sure what information is needed here, however, so please do ask what you need and I'll be happy to provide additional details where I can.

**Comment by nt1m** [comment]
@LarnuUK Have you tried updating Firefox Color? (Add-ons manager -> menu -> "Check for updates")

**Comment by Rob--W** [comment]
> I doubt that this is an API issue, due to the fact that I can only replicate the issue on one computer (the Windows instance at work).

Is Firefox Color at the latest version? It sounds like you're using an old version. The current version is [2.1.5](https://addons.mozilla.org/en-US/firefox/addon/firefox-color/versions/2.1.5/), which is designed to be compatible with old and new versions of Firefox, including support for previously saved themes.

**Comment by LarnuUK** [comment]
It should be up to date as I have automatic updates on, however, I will verify when I'm at the office tomorrow.

**Comment by LarnuUK** [comment]
> 
> 
> @LarnuUK Have you tried updating Firefox Color? (Add-ons manager -> menu -> "Check for updates")

Oddly, no, it's not up to date and when clicking update it says there are no updates available. explains why it's not working, but odd that it isn't updating. I'll have a look, but if anyone know where I can manually download the files for the extention, that'll be great.

Thanks.

**Comment by Rob--W** [comment]
@LarnuUK Could you open your profile directory and attach the extension here (or mail it to me)? Then I can tell what's happened. Please don't update yet, I want to know if there is a bug that we need to fix.

You can find the profile directory at `about:profiles` . There should be a directory called "extensions", and inside there should be something like `FirefoxColor@mozilla.com.xpi`

**Comment by LarnuUK** [comment]
> 
> 
> @LarnuUK Could you open your profile directory and attach the extension here (or mail it to me)? Then I can tell what's happened. Please don't update yet, I want to know if there is a bug that we need to fix.
> 
> You can find the profile directory at `about:profiles` . There should be a directory called "extensions", and inside there should be something like `FirefoxColor@mozilla.com.xpi`

Think I might have homed in on it here, actually, @Rob--W . Looks like that Firefox has "recently" been classified as "freeware" by our firewall vendor, and so http://firefox.com and it's respective subdomains are being blocked. After a little testing, I've also noticed that Firefox itself is failing to check for updates (and is stuck at 70.0.0). There's quite a few of us that use Firefox in the office, and ensuring they patch is critical for security, so I've passed this up to the Network Administrator to whitelist the domain. Hopefully that'll fix the issue (I'll leave open till it's whitelisted if that's ok, in case it isn't the issue,, but may be a few days before completion).

If you still want me to get the extension attachment still, please let me know, however, this seems like a very likely candidate.

Many thanks.

**Comment by Rob--W** [comment]
That sounds quite likely the cause of the problem. And it is indeed a big security risk at the part of your office.

I'll close this bug since there is probably not anything actionable for us, but if you have any more information, do feel free to add a comment and I'll see it.

**Comment by LarnuUK** [comment]
Thanks Rob, I'll confirm either way.

**Comment by Rob--W** [comment]
Could you also send the details (maybe by mail) of the firewall that causes the issue? If this affects more people than just your office, I think that the knowledge may be useful to other people at Mozilla.

**Comment by LarnuUK** [comment]
Brand we use is SonicWall, @Rob--W . I can get try to get more details and email them across at a later date, if that helps.
