### ISSUE TITLE
Color by Domain

### ISSUE THREAD

**Issue by erayerdin** [mozilla/FirefoxColor#873]
It would be nice to have Firefox change color specific to particular domains. For instance, blue dominant color scheme for Facebook, purple dominant color scheme for Instagram etc.

**Comment by caitmuenster** [comment]
Hey @erayerdin, that sounds like it would be really useful! That's a little outside of the scope of Firefox Color but you may be able to find an extension solves that issue on addons.mozilla.org or by asking the community on our [forums](https://discourse.mozilla.org/c/add-ons).
