### ISSUE TITLE
Last page of "Saved themes" tab is not removed after you delete all listed themes

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/FirefoxColor#881]
**Affected versions:**
Firefox Nightly 74.0a1 - Build ID 20200109213942

**Affected Platforms:**
All Windows
All Mac
All Linux

**Steps to reproduce:**
1. Navigate to color.firefox.com 
3. Have in "Saved themes" tab, more than 3 pages. (an easy way to do this is to randomly generate and save themes)
4. Navigate to last page and delete all themes from that page.

**Expected results:**
User is redirected to previous page.
Navigation section shows active page.

**Actual result:**
A blank page is displayed. Navigation section does not show an active page.

**Notes:**
This issue is also reproducible after "Firefox Color" add-on installation.
Attaching a screenshot with the issue.
![delete themes](https://user-images.githubusercontent.com/15685960/72153386-849a7180-33b6-11ea-928f-8f84e6d4ca95.png)

**Comment by SoftVision-CarmenFat** [comment]
- After investigating this issue more, we noticed that if the user has only 2 pages containing saved themes and deletes the themes from the second page, the navigation buttons are no longer displayed.
- Just switching between the Color tabs and focusing the "Saved themes" back doesn't bring back the navigation buttons, nor the first page with the remaining saved themes.
- The remaining page with the saved themes is displayed only after performing a reload of the Color page.
- Considering this, I will upgrade the severity of the bug from minor to normal issue. 

![color saved themes](https://user-images.githubusercontent.com/26000308/74839287-b5fb4b00-532d-11ea-83ff-f1d4e2130e94.gif)

**Comment by ValentinaPC** [comment]
I have verified the issue, and it is still reproducible, using Firefox Nightly 76.0a1 ( Build ID20200402095145) on -stage (https://color.stage.mozaws.net/) and -dev (https://mozilla.github.io/FirefoxColor/) by updating the add-on to point to these environments in Windows, Mac and Linux.

**Comment by ValentinaPC** [comment]
I have verified the issue, and it is still reproducible, using Firefox Nightly 76.0a1 ( Build ID20200402095145) on -stage (https://color.stage.mozaws.net/) and -dev (https://mozilla.github.io/FirefoxColor/) by updating the add-on to point to these environments in Windows, Mac and Linux.

**Comment by ValentinaPC** [comment]
I have verified the issue, and it is still reproducible, using Firefox Nightly 76.0a1 ( Build ID20200402095145) on -stage (https://color.stage.mozaws.net/) and -dev (https://mozilla.github.io/FirefoxColor/) by updating the add-on to point to these environments in Windows, Mac and Linux.

- if we have saved themes on 2 pages, deleting all themes from the last page will not redirect the user to first page , a blank page will be displayed without the possibility to get out of there.
![saved](https://user-images.githubusercontent.com/15685960/78330691-3f3ca900-758d-11ea-829e-3d5da1a629f4.png)

- If we have saved themes on 3 pages or more, deleting the themes from the last page will not redirect the user to the previous page, navigation points not indicating the page position, but clicking on any nav point will take the user to corresponding page.
![4 pages](https://user-images.githubusercontent.com/15685960/78330695-45328a00-758d-11ea-9729-73f20ea81518.png)

**Comment by rebmullin** [comment]
Hi @ValentinaPC, can you please check this again? This was not deployed to stage before today..

thank you!

**Comment by SoftVision-SimonaRosu** [comment]
I have verified this issue on the stage server of the Firefox Color website and is no longer reproducible. Tested using the latest Nightly 77.0a1 (Build ID: ), Firefox RC 76 (Build ID: 20200427162639), Firefox Release 75 (Build ID:) on Windows 10 x64, Ubuntu 18.04 x64, Mac 10.14.6.
- After all the themes are deleted from the last page, you are correctly redirected to the previous one.
- The themes from the first page are shown after deleting the themes from the second page.

However, the issue is still reproducible with the production version. Can you please confirm if the fix wasn’t deployed to prod?

**Comment by Rob--W** [comment]
I can confirm - this has not been deployed to prod yet:

- The prod branch is still at Feb 29 - https://github.com/mozilla/FirefoxColor/tree/production
- The stage branch is up to date, Apr 29 - https://github.com/mozilla/FirefoxColor/tree/stage
