### ISSUE TITLE
New Megabar is not themed

### ISSUE THREAD

**Issue by happysurf** [mozilla/FirefoxColor#885]
The new Megabar active by default from Firefox 74beta+ is independent from FirefoxColor theme system, this is a very a bad news.
At moment I have solved this problem with this code in userchrome.css:

```
/* Megabar custom background */
.urlbarView.megabar{
background-color: #yourcolor !important;
margin-bottom: 7px !important;
}
```

Any plans to embed megabar on FirefoxColor?

**Comment by Rob--W** [comment]
What theme are you using? When I change "Search Bar Color" at https://color.firefox.com/ , then the (expanded) megabar has the expected color.

**Comment by happysurf** [comment]
> 
> 
> What theme are you using? When I change "Search Bar Color" at https://color.firefox.com/ , then the (expanded) megabar has the expected color.

With my theme Solarize Fox (exported by FirefoxColor addon) https://addons.mozilla.org/en-US/firefox/addon/solarize-fox/ the drop down menu is black.

**Comment by Rob--W** [comment]
Your theme has the following "Search Bar Color" declaration:
```
            "toolbar_field": "rgba(0, 0, 0, 0.66)",
```

That is... black with 66% transparency. It is rendered as expected - in Firefox Nightly 74.0a1 buildID 20200206093813 (see `about:support`) the megabar has a dark background with your theme.

**Comment by happysurf** [comment]
OK, I have rewrite my theme for fix the problem.
Thanks.
