### ISSUE TITLE
The tooltips of the Warning icon next to the uploaded image are incorrect after trying to upload incompatible files 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/FirefoxColor#888]
[Affected Platforms]:
- Windows 10 x64
- Ubuntu 16.04 x64
- macOS 10.14

[Affected Versions]:
- Firefox Nightly 75.0a1 (2020-02-19) Build ID 20200219095352
- Firefox Beta 74.0b5 , Build ID 20200218224219 
- Firefox Release 73.0.1 Build ID 20200207195153

[Prerequisites]:
- Have the latest version of the Firefox Color add-on modified in order to link to the stage website.
- Have the previous Firefox Color add-on installed through "about:debugging".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to the https://color.stage.mozaws.net/ website.
3. Navigate to "Custom backgrounds" tab and click the "...Or add your own" button.
4. Upload a picture up to 1MB (jpg, png or bmp).
5. Click the "Replace image" button.
6. Upload a file bigger than 1MB.
7. Hover the Warning icon from the left side of the image's thumbnail.
8. Click the "Replace image" button.
9. Upload a file that is not an image (eg. xpi, zip, pdf, js etc).
10. Hover the Warning icon from the left side of the image's thumbnail.

[Expected result]:
- Step 7 - The Warning tooltip contains the same text as the error message "The image is too large (1MG maximum size)" OR nothing happens.
- Step 10 - The Warning tooltip contains the same text as the error message "The file is not an accepted image type" OR nothing happens.

[Actual result]:
- Step 7 - {"too large":true, "wrongType":false} tooltip is displayed.
- Step 10 - {"too large":false, "wrongType":true} tooltip is displayed.

[Notes]:
- I have attached a screen recording of the issue:

![color](https://user-images.githubusercontent.com/26000308/74836830-daa0f400-5328-11ea-828b-41de9c55b517.gif)

**Comment by SoftVision-CarmenFat** [comment]
- This issue is still reproducible with the latest version of the "Firefox Color" add-on (v.2.1.5) installed, on the latest Firefox Nightly 76.0a1 (2020-04-02) using both Dev and Stage servers. 
- Considering this I am reopening the issue.

**Comment by Rob--W** [comment]
Neither the stage nor the dev branches have been updated yet.

stage was last updated in February, 29th.
dev was last updated a year ago (april 2019).

**Comment by rebmullin** [comment]
can you please check again? We just did a release to stage..

thank you!

**Comment by heres-maria** [comment]
I have verified this issue is no longer reproducible on the stage server of the Firefox Color website. The tooltips now display the correct messages. 
Tested using Nightly 77.0a1 (Build ID: 20200504093644 ), Firefox RC 76 (Build ID: 20200429185419), Firefox Release 75 (Build ID: 20200403170909) on Windows 10 x64, Mint 19.2, Mac 10.14.6.

**Comment by caitmuenster** [comment]
Thank you @heres-maria!
