### ISSUE TITLE
Give themes names (<140 chars)

### ISSUE THREAD

**Issue by 6a68** [mozilla/FirefoxColor#91]
Would be really easy to wedge into a URL, and makes the theme creation / selection more evocative

**Comment by johngruen** [comment]
As long as we can name at least one them _Miami Nightmare_ i'm good with this...

We could give names to all the preset themes anyway and let just the names be shared instead of the hash?

**Comment by lmorchard** [comment]
> We could give names to all the preset themes anyway and let just the names be shared instead of the hash?

That wouldn't be too hard to do, though I do like having the sharing scheme be consistent across themes.

**Comment by pdehaan** [comment]
As of #111, we have a `title` property for the preset themes.

**Comment by lmorchard** [comment]
Yeah, we have the property in data, but not really a good story for displaying them. We also talked a bit about what adding titles to saved themes would take in terms of saving & editing UI
