### ISSUE TITLE
Support other properties from the URL even if the UI does not like ntp_ ones

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/FirefoxColor#923]
If I visit this URL

https://color.firefox.com/?theme=XQAAAAKEAwAAAAAAAABBqYhm849SCicxcUV5wYurLpubfikoJrYDaXef7eDwUAjshNvI2R1-qq64xJcRb6iFRYLtb_2uPCIluCEjcsDFhxGAKMrYS8NozTghHsnboe7DXFl_DJxNDhj3ISa2-Y1jhjzCKx_Owt6rCmfzvQKMUtPQkskDCwjepZb-j1ucSfa4-ID1aN-qQ9aiRpUq20b8egfX-XhyZAujr68cTFrCEODOce4x7AncvKoiLElwJNJ1pSIqMo1khLnCPZsqsa5CrfWMdOsQsor0B4Mw5i36fNepTl44I-ZelGkPO7gtegjdtF44Ezr96Tv4rktLrQS4Pjr1q2O0pNxCfUhGw4MaW9MmJUXoN8kbfZyDy1mFy3DMMzUU_dSiVEyZXw-qjJXxL-ukSoZpR-OX8Wrx4s3AI5_DugvZedKR5wPBr5k10dgUa-YplllcjaSZc8-Rf4KjirpFcAiraNM7-4OsuUslFyDh_uKTyg

I expect the UI to look like this

![image](https://user-images.githubusercontent.com/922368/79923096-835cf400-843d-11ea-8417-8bc0f6cc9971.png)

In reality it looks like this:
![image](https://user-images.githubusercontent.com/922368/79923183-b8694680-843d-11ea-8e34-48650670df5a.png)

The problem seems to be here https://github.com/mozilla/FirefoxColor/blob/master/src/preset-themes/default.json

Would you accept a PR?
The reason I want this feature is that it would be nice for themer.dev to be able to generate more complete themes and share them trough color.firefox.com and not necesarily require an AMO account. Here is the relevant comment https://github.com/mjswensen/themer/issues/48#issuecomment-617338335

The list of props I'm currently interested in adding is:

bookmark_text
frame_inactive
icons_attention
icons
ntp_background
ntp_text
popup_highlight_text
popup_highlight
toolbar_field_highlight_text
popup_border
sidebar_border
sidebar_highlight_text
sidebar_highlight
sidebar_text
sidebar
tab_loading
tab_text
toolbar_bottom_separator
toolbar_field_border
toolbar_field_separator
toolbar_field_text_focus
toolbar_field_border_focus

They don't necessarily need to be in the web ui. I'll stick to whatever is now the default. All I want to do is the extension to be able to render an URL like the one above and create the full theme, not a partial one.

**Comment by kinduff** [comment]
I see a lot of potential in FirefoxColor and the attributes that @andreicristianpetcu is listing would make it a more usable tool for creators and power users.

I've seen Andrei's work and he's remarkable, would love to see a PR from him in this project.

**Comment by mjswensen** [comment]
Agreed. For example, currently [themer](https://github.com/mjswensen/themer) supports both Color and a full add-on, simply because Color is relatively limited. Would love to see better support for full themes since Color is so convenient to use.

Also, +1 on @andreicristianpetcu , if he has the time to work on this — gets the job done and gets it done quick.

**Comment by Rob--W** [comment]
We are willing to accept pull requests to provide support for properties beyond the currently supported ones, provided that the proposal has a reasonable UI and UX.

Every supported property must explicitly be listed in the code (unrecognized properties should not be supported). The user should clearly be able to see that a theme has more properties besides the default ones, and they should be able to modify the value.

When a theme is exported, the exported theme should only contain a new property if it has an explicit value. In other words, if the user does not use any of the new properties, the exported theme should be similar to what the website exports today.

The Firefox Color website offers preview functionality. You don't have to implement this for every property. When a property without preview is used, the UI should clearly indicate this as such, and recommend the user to install the Firefox Color add-on.

**Comment by andreicristianpetcu** [comment]
How about this:
- toolbar_field_separator = toolbar_field
- toolbar_bottom_separator = toolbar
- ntp_background = new item in the UI
- ntp_text = new item in the UI

Here is a mockup
![image](https://user-images.githubusercontent.com/922368/80275981-ebd1fc80-86ed-11ea-8e77-eedf50d0493e.png)

**Comment by Rob--W** [comment]
What about the other properties from your first comment?

> toolbar_field_separator = toolbar_field
> toolbar_bottom_separator = toolbar

They can be set independently, so I would prefer to have them as separate options, possibly with an option to default to the other theme if not set, e.g. like this:

```
Default:
[icon] toolbar_field_separator
( icon = some icon that signals that this is a reference to an external color)
( toolbar_field_separator = the human-readable name )
```

When [icon] is clicked, the color picker is shown, but there is also an option to select an existing color definition. There should be a reset button to reset it to the default (i.e. to remove the explicit override from the theme definition).

Adding more options is good for customability, but a too crowded UI is confusing for users who are just starting out. An easy way to strike the balance between them is to add a new section "Advanced" (collapsed by default), where you put all properties that you want to support.

**Comment by andreicristianpetcu** [comment]
I'm trying to get here the simplest thing that could possibly work. The goal is not to break old behavior. Here's my proposal based on your comments:

![image](https://user-images.githubusercontent.com/922368/80310338-c07d0980-87e2-11ea-9672-57431fbd3f8d.png)

I can add the full list in the UI, even if the values are not previewed.

I think reset to default is a nice improvement idea but maybe out of scope for this one.

**Comment by andreicristianpetcu** [comment]
I added the 4 I mentioned above since these are the ones I care about most. Here is the diff https://github.com/mozilla/FirefoxColor/compare/development...andreicristianpetcu:advanced_colors?expand=1

Here is how it looks. Is this a good direction? Should I add the rest?
I need to work on the default colors so that I don't break existing themes.  ntp_text and ntp_background work as expected but the other two don't have the correct default colors.
![theme](https://user-images.githubusercontent.com/922368/80315890-33967800-8803-11ea-9a37-b442e6034b09.gif)

**Comment by Rob--W** [comment]
> I'm trying to get here the simplest thing that could possibly work. The goal is not to break old behavior. 

> I need to work on the default colors so that I don't break existing themes. ntp_text and ntp_background work as expected but the other two don't have the correct default colors.

Old behavior is "broken" (i.e. changed) when anything is added to `default.json`. This is what I wrote in paragraph 3 in my initial reply: https://github.com/mozilla/FirefoxColor/issues/923#issuecomment-617797335

To support new properties without adding them to default.json, the [`normalizeThemeColors`](https://github.com/mozilla/FirefoxColor/blob/cb5a6437739569629b315b895e6c0f2f1d612a3c/src/lib/themes.js#L130) should be modified. To make sure that it works and continues to work as expected, add a unit test to https://github.com/mozilla/FirefoxColor/blob/ece86cc2c447448c888aeda60230b6342684248e/src/lib/themes-test.js

and because there is a difference between a selected color and "nothing", the UI must have a way to reset the color (i.e. delete the property from the theme opposed to having a color value there). This is a must-have, because otherwise users won't be able to remove an advanced color from their theme.

PS. What is the "Raw Theme Data" tab? It looks useful as an advanced-advanced feature ;)

**Comment by andreicristianpetcu** [comment]
Will look into normalizeThemeColors.
Raw theme data only runs on localhost. I did not add it.

**Comment by andreicristianpetcu** [comment]
How is this for you, @Rob--W ? Is this going in the direction you mentioned? 
I removed the colors from default.json and used normalizeThemeColors here is the diff https://github.com/mozilla/FirefoxColor/compare/master...andreicristianpetcu:advanced_colors

TODO:
 - The [x] for not color present is ugly, I'll find some nice SVG
 - I'll use the same SVG as above in the preset color section to offer the "delete" option for the advanced colors
 - unit test.

![color](https://user-images.githubusercontent.com/922368/81481804-4b2a2380-923b-11ea-8b51-21118d166dc1.gif)

**Comment by Rob--W** [comment]
Looks like the right direction.

Do you intend to add more colors beyond those four? The reason for the advanced colors tab is to have the ability to customize potentially anything that Firefox supports. Possibly with a search box to filter by color description if needed, and of course a notice that previewing the theme requires Firefox color to be installed.

**Comment by andreicristianpetcu** [comment]
Yes, I want to add more colors. Search box seems like an extra feature, not part of this. It's an improvement. I can add a notice.

**Comment by andreicristianpetcu** [comment]
@Rob--W This is what I have until now. You said you wanted an option to reset or delete the color. Where do you want me to put this icon? Currently once you set an advanced color, you cannot unset it.

![color2](https://user-images.githubusercontent.com/922368/81490426-eac2d280-928a-11ea-98a0-983d30dcb06c.gif)

**Comment by andreicristianpetcu** [comment]
this is the icon. https://fontawesome.com/icons/paint-brush?style=solid I did not find how to add attribution to it since it's CC BY 4.0. Will look into that before I merge.

**Comment by andreicristianpetcu** [comment]
something like this for the delete/undo?
![image](https://user-images.githubusercontent.com/922368/81490677-bac8fe80-928d-11ea-888f-b688bd1866a8.png)

**Comment by andreicristianpetcu** [comment]
Or maybe this since the undo icon might create confusion with the one at the top right.
![image](https://user-images.githubusercontent.com/922368/81490709-05e31180-928e-11ea-9402-8601bcaa46ab.png)

**Comment by andreicristianpetcu** [comment]
I implemented the revert. It only works for advanced colors.
![color3](https://user-images.githubusercontent.com/922368/81493433-04731280-92a9-11ea-9ac3-41165cf362ec.gif)

**Comment by andreicristianpetcu** [comment]
@Rob--W I added the test that you asked. The CI is passing. Here is the PR https://github.com/mozilla/FirefoxColor/pull/929
