### ISSUE TITLE
Toolbar bottom separator

### ISSUE THREAD

**Issue by esteiner44** [mozilla/FirefoxColor#930]
Good Morning,

When I select a background color, the toolbar bottom separator also gets that color and creates an unsightly effect. I would like, if possible, for more elements to be added for customization or for the separator to not get the background color.

Best regards

**Comment by mitchell-frost** [comment]
I would like to work on this but can I have a little more details?

**Comment by esteiner44** [comment]
When you change the "Background Color" property (image 1, arrow 1) you also change the color of the tool separator (image 1, arrow 2).

![1](https://user-images.githubusercontent.com/66116964/83271152-bd9e7b80-a1c9-11ea-834b-6a141806421c.jpg)
At first I thought it was part of the program's interface but it is not because it happens on all pages (image 2, arrow 1). I have noticed that in other topics this does not happen and investigating a little I have seen that the property that allows to change the color of the separator is called "Toolbar bottom separator" and the color of that property is similar to that of arrow 2.

![2](https://user-images.githubusercontent.com/66116964/83271174-c3945c80-a1c9-11ea-98fa-38eecb0b3fcf.jpg)
I could not test more on my own because I cannot install the themes that are exported, I get an error from mozapps that says that the file is damaged, although that will be because I am not doing something right :).

What I wanted to know is if you can add more options, change more elements per separator, like the color of that separator, or at least that the color of that bar doesn't change at the same time as the background.

**Comment by mitchell-frost** [comment]
I will take a look at this and see if I can reproduce the issue.

**Comment by esteiner44** [comment]
I have not done anything special, changing the "Background color" property also changes that line.

For help, this is a screenshot of a downloaded theme and it doesn't have the line.

![3](https://user-images.githubusercontent.com/66116964/83307214-800b1400-a204-11ea-984c-a73c7414c321.jpg)
And this is a theme created with the program and as you can see if the line is there.

![4](https://user-images.githubusercontent.com/66116964/83307221-86998b80-a204-11ea-8563-5d3b49e444a6.jpg)
Looking at the code of the downloaded theme I saw the property "Toolbar_bottom_separator" and when changing it I can change the color of the line, the problem is that the themes created with the program do not have that property. So I wanted, if possible, to add the option to change that line color or at least not take the background color because the look is a bit ugly.

**Comment by Rob--W** [comment]
This is now possible as of Firefox Color 2.1.6. You can customize all colors that Firefox supports through FirefoxColor. Can you confirm that this works as desired?

**Comment by esteiner44** [comment]
Yes now you can change the color of the bar! Thank you very much, I think that now it is the best extension that exists to create themes in Firefox, it has a clear interface and allows you to customize everything, it is incredible. Although the other extensions that I have seen are also very good, I keep this one.

Best regards
