### ISSUE TITLE
“Revert All” button reverts to default theme even if another theme was previously installed and enabled

### ISSUE THREAD

**Issue by acornestean** [mozilla/FirefoxColor#935]
Preconditions:
1. Go to about:config and change the “xpinstall.signatures.required” pref to “false”
2. Access https://color.stage.mozaws.net/
3. Click on the “Advanced colors” tab
4. Click on “Firefox Color Extension” link from the right side panel
5. On the newly opened page, click on “Unsigned add-on for color.stage.mozaws.net “
6. Follow the instructions on the doorhangers and install the Firefox Color add-on

Steps to reproduce:
1. Go to about:addons → Themes tab
2. Install any recommended theme OR enable any of the default Firefox themes (Dark or Light) OR install any theme from AMO
3. Access https://color.stage.mozaws.net/
4. Create a custom theme
5. Click on the “Revert All” button
6. Observe that Firefox reverts to the default theme and not to the previously set theme from Step 2
7. Go to about:addons → Themes tab
8. Observe that the theme installed in Step 2 is still enabled but not applied and disabling it will immediately enable the default theme

NOTE: Pressing the “Revert All” button before any custom theme elements have been set will do nothing but re-load the Firefox Color page.

Expected results:
Clicking the “Revert All” button should revert Firefox to the last applied theme.
 
Actual results:
Clicking the “Revert All” button will revert Firefox to the default theme instead of the last applied theme. 
The last applied theme is still shown as enabled in about:addons.

Affected versions:
- Nightly 79.0b1/20200629224419
- Beta Developer Edition 80.0a1/20200629154604
- Release Unbranded 77.0.1/20200602222727

Affected OSes:
- Windows 10 64-bit
- Ubuntu 16.04 LTS

Due to a larger file size, I'm attaching an archive of the screen recording.

[Revert All.zip](https://github.com/mozilla/FirefoxColor/files/4857443/Revert.All.zip)

**Comment by acornestean** [comment]
The issue also occurs on macOS Catalina 10.15 as well.

**Comment by Rob--W** [comment]
This is a limitation of Firefox. Firefox Color overrides the global default theme. At that point, Firefox doesn't know about the previous default theme any more, so when the theme is reset, the default (non-custom) theme is used instead.

There is some relevant discussion upstream at https://bugzilla.mozilla.org/show_bug.cgi?id=1415267
