### ISSUE TITLE
“Tab Loading” property is not functional

### ISSUE THREAD

**Issue by acornestean** [mozilla/FirefoxColor#936]
Preconditions:
1. Go to about:config and change the “xpinstall.signatures.required” pref to “false”
2. Access https://color.stage.mozaws.net/
3. Click on the “Advanced colors” tab
4. Click on “Firefox Color Extension” link from the right side panel
5. On the newly opened page, click on “Unsigned add-on for color.stage.mozaws.net “
6. Follow the instructions on the doorhangers and install the Firefox Color add-on

Steps to reproduce:
1. Access https://color.stage.mozaws.net/
2. Click on the “Advanced colors” tab
3. Scroll to the “Tab Loading” property and set a color for it, for example Yellow
NOTE: This property is responsible for the tab loading indicator (short back and forth animation) and tab loading color burst when loading/reloading tabs. 
4. Open a new tab and go to https://www.youtube.com/
5. Reload the page
6. Observe that the color set through the “Tab Loading” property was not applied
NOTE: 
The actual color of the tab loading indicator and tab loading burst are set through 2 properties from the “Custom colors” tab:
- the tab loading indicator color is set through the “Toolbar Icons and Text” property
- the tab loading burst color is set through the “Tab Highlight Color” property

Expected results:
The color set through the “Tab Loading” property should be properly applied to the elements it is responsible for i.e. the tab loading indicator and tab loading color burst as described in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors “tab_loading” section.

Actual results:
The color set through the “Tab Loading” property is not applied.

Affected versions:
- Nightly 80.0a1/20200701093012
- Beta Developer Edition 79.0b2/20200630191632
- Release Unbranded 77.0.1/20200602222727

Affected OSes:
- Windows 10 64-bit
- Ubuntu 16.04 LTS

![2020-07-01_15h51_46](https://user-images.githubusercontent.com/50236075/86246201-489cd800-bbb3-11ea-86e5-2db0a88e7331.png)

![2020-07-01_15h52_04](https://user-images.githubusercontent.com/50236075/86246217-4dfa2280-bbb3-11ea-93ef-2b854cdcb1d1.png)

![tab loading](https://user-images.githubusercontent.com/50236075/86246253-5fdbc580-bbb3-11ea-98b9-d7f5469d2d02.gif)

**Comment by acornestean** [comment]
The issue also occurs on macOS Catalina 10.15 as well.

**Comment by andreicristianpetcu** [comment]
I found the problem. Would this fix be enough + a unit test? @Rob--W https://github.com/mozilla/FirefoxColor/pull/940/files

**Comment by andreicristianpetcu** [comment]
Nice find! @acornestean

**Comment by acornestean** [comment]
Verified the fix on the latest Nightly (80.0a1/20200716094032), Beta Dev Edition (79.0b8/20200714212005) and Unbranded Release (78.0.2/20200708170202) under Windows 10 Pro 64-bit and Ubuntu 16.04 LTS.

The loading burst color is now properly set through the “Tab Loading” property from the “Advanced color” tab, HOWEVER, there is an issue with the loading indicator color, which manifests in 2 ways, at random, as far as I’ve noticed:

1. The loading indicator starts with the color set through the “Toolbar Icons and Text” property from the “Custom colors” tab and throughout the animation it changes the color to the one set through the “Tab Loading” property from the “Advanced color” tab.

OR

2. The loading indicator starts with the color set through the “Toolbar Icons and Text” property from the “Custom colors” tab and throughout the animation it DOESN’T change the color to the one set through the “Tab Loading” property from the “Advanced color” tab but remains the same until the loading burst.

Please see the attached screen recordings and screenshot.

- loading indicator changes color throughout the animation
- loading indicator doesn’t change color throughout the animation

**Comment by andreicristianpetcu** [comment]
no clue how this color change happens. 100% sure it's not from ff color
