### ISSUE TITLE
Awesomebar autocomplete text missing background colour

### ISSUE THREAD

**Issue by chutten** [mozilla/FirefoxColor#941]
Without Firefox Color, my awesome bar autocompletes like so:

![image](https://user-images.githubusercontent.com/1123376/88188520-f5dc9c00-cc05-11ea-9dee-3d70aff7de5e.png)

With Firefox Color, my awesome bar autocompletes like so:

![image](https://user-images.githubusercontent.com/1123376/88188581-0ee54d00-cc06-11ea-9f77-82183831a622.png)

It's not so visually distinct and I'm not sure when exactly it started doing it that way.

I've now (finally) perused the documentation and found that the parameter name is "Toolbar Field Highlight" and it is indeed customizable... but the default value appears to be transparent instead of the same colour as "Popup Highlight". 

I would expect that "Use Firefox's default style" would actually use Firefox's default colour for the toolbar field highlight.

**Comment by Rob--W** [comment]
Could you export and share the theme?

Has it always happened, or did it only start to happen recently? The new version of Firefox Color, 2.1.6 was released only a couple hours ago.

**Comment by chutten** [comment]
This has been happening for some weeks, I've just been ignoring it until now : |


[theme.zip](https://github.com/mozilla/FirefoxColor/files/4960726/theme.zip)

Here's the theme with the added "Toolbar Field Highlight" colour

**Comment by chutten** [comment]
Go to color.firefox.com with the theme, under "Advanced Colours" set "Toolbar Field Highlight" to "Use Firefox's default style"

I... _think_ this one has the bug, but I'm not sure if I have to "Save" it before Export:
[theme(1).zip](https://github.com/mozilla/FirefoxColor/files/4960907/theme.1.zip)

**Comment by Rob--W** [comment]
> under "Advanced Colours" set "Toolbar Field Highlight" to "Use Firefox's default style"

Works for me, in Firefox 78.0.2 and Nightly on Linux and macOS. In all cases I see the default (blue) background when I choose "use Firefox's default style".

In Firefox Color 2.1.5 and earlier, or 2.1.6 + "Use Firefox's default style", the browser is not passed an explicit value for the `toolbar_field_highlight` theme property, and Firefox's default is used, whatever that may be.

**Comment by chutten** [comment]
This was specifically on Windows 10, not sure if that made a difference (it shouldn't). "use default" reliably gets me to a transparent highlight. I wonder if maybe something's borked on my Beta somewhere else.

**Comment by Rob--W** [comment]
I managed to reproduce with the same extension. For the lack of theme importing functionality, I tried to manually create your theme but probably made a mistake. I created a script to convert the theme to a format that Firefox Color recognizes and managed to reproduce the issue. Then I did some trial and error,and found that the following theme (independently of Firefox Color) reproduces the issue:

```
{
  "manifest_version": 2,
  "version": "1.0",
  "name": "chutten_with_bug_i_think",
  "theme": {
    "colors": {
      "toolbar": "rgb(250, 250, 250)"
    }   
  }
}
```

The background defaults to the `Highlight` color: https://searchfox.org/mozilla-central/rev/dcd9c2d2bc19d96d487825eb70c2333a4d60994e/browser/themes/shared/urlbar-searchbar.inc.css#117

The `Highlight` color is apparently dependent on the value of the `toolbar` color. If not completely light, the "Highlight" color becomes some light-ish color. To fix this, you can override the "Toolbar Field Highlight" color with the desired color value.

**Comment by chutten** [comment]
So by setting the "Search Bar Color" I was also setting the "Toolbar Field Highlight" unknowingly? Interesting.

If this is operating as designed and expected I'm happy to have this closed out if you want.

**Comment by Rob--W** [comment]
> So by setting the "Search Bar Color"  I was also setting the "Toolbar Field Highlight" unknowingly?

"Toolbar Color", apparently.

Looks like it works as intended from Firefox Color's side.
