### ISSUE TITLE
Saved themes not accessible

### ISSUE THREAD

**Issue by sinky** [mozilla/FirefoxColor#952]
The fake menu is overlaying the "Saved themes" Tab

![Screenshot_2020-09-05 Firefox Color](https://user-images.githubusercontent.com/822246/92312558-2c0d8980-efc2-11ea-9e0c-ee7ded5eb54d.png)

![Screenshot_2020-09-05 Firefox Color(1)](https://user-images.githubusercontent.com/822246/92312560-2f087a00-efc2-11ea-9665-cec81a585466.png)

**Comment by sinky** [comment]
i just noticed i was on 110% page zoom

**Comment by nullbasis** [comment]
This is an issue for me at 100% zoom. I have to go down to 80% to fix it.
