### ISSUE TITLE
Random function should generate themes with enough contrast

### ISSUE THREAD

**Issue by dannycolin** [mozilla/FirefoxColor#953]
** Step to reproduce**

0. Go to Firefox Color theme generator
0. Click on random

**Actual Behavior**

Most of the time the generated theme has a foreground and background color with a contrast so low that you can't even read the text. This is problematic in term of accessibility but also in term of UX because it forces the user to manually change on almost every generated theme.

**Expected Behavior**

We should make sure that auto-generated themes have a minimal (pre-determined) contrast ratio (e.g. WCAG AA). So every theme generated could be used as is by the user without the need to manually change colors.

**Comment by Rob--W** [comment]
This looks like a reasonable request. It does seem that there is already some form of support for accessible themes, but it runs only 50% of the times:
- https://github.com/mozilla/FirefoxColor/blob/e5f198cf524fc570cf3c9b763a3f03465b000fba/src/web/lib/components/AppHeader/index.js#L35-L39
- https://github.com/mozilla/FirefoxColor/blob/d781645d68381d24712d668fe09043c5803ddebb/src/lib/generators.js

Is the theme generator almost always creating inaccessible themes, or is it closer to 50%?

**Comment by dannycolin** [comment]
> Is the theme generator almost always creating inaccessible themes, or is it closer to 50%?

When I tried it felt like more than 50%. Maybe it was due to the fact that even if I don't have any visual impairment the contrast was still too low for my use case -> on a laptop with low brightness.
