### ISSUE TITLE
[feature request] Missing Sidebar background color customization

### ISSUE THREAD

**Issue by carlesba** [mozilla/FirefoxColor#954]
I can't find the sidebar background color, ie: bookmarks sidebar background. According to the [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors) this is customizable. 
Is there any plan to add this?

Thanks for the extension, it's pretty cool!

**Comment by Rob--W** [comment]
Have you looked at the Advanced colors tab?

**Comment by carlesba** [comment]
yes, you can set some of the panel colors like the border but the background is not defined as option

**Comment by Rob--W** [comment]
I am able to change the sidebar's background by choosing a color for the "Sidebar" option (scroll down at the "Advanced colors" tab if you can't see it). If it doesn't work for you, could you describe which sidebar you're trying to paint?

**Comment by carlesba** [comment]
I cannot find it:

<img width="1602" alt="Screenshot 2020-09-30 at 18 17 50" src="https://user-images.githubusercontent.com/1178459/94712233-7d066880-0349-11eb-9736-97d5bb739ae9.png">

**Comment by Rob--W** [comment]
Although the scrollbar isn't visible (are you using Firefox on macOS?), there is a scrollable area containing those colors. The scrollbar is at the left of the grey panel.

**Comment by carlesba** [comment]
🤦 sorry…
thanks @Rob--W
