### ISSUE TITLE
New tab background color

### ISSUE THREAD

**Issue by naoliv** [mozilla/FirefoxColor#957]
Unless I am misunderstanding something here, it's not possible to customize the new tab background color? (which is white, by default)

For example, when trying to create a darker theme I couldn't get rid of this white background (on the `about:blank` tabs):

![](https://user-images.githubusercontent.com/982338/92979255-74b4bf00-f468-11ea-9e1f-2f00b909e47e.png)

**Comment by Rob--W** [comment]
The background color of the `about:blank` page is not controlled by themes, but by whether your system is using a dark theme.

If you have not or cannot changed your system's "dark theme" setting, then you can force the dark theme to be enabled as follows:

1. Visit `about:config`.
2. Put `ui.systemUsesDarkTheme` in the input box, and set it to 1.

This preference does not only change the appearance of `about:blank`, but it will also change the colors of any website that has declared a dark theme via https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by naoliv** [comment]
Interesting! I didn't know this.
Probably this issue could be closed then?
Thank you a lot!
