### ISSUE TITLE
The “Learn More” button on Unsupported Website page incorrectly redirects to FPN

### ISSUE THREAD

**Issue by reinhart1010** [mozilla/FirefoxColor#958]
When clicking the "Learn More" button in an "Unsupported Browser" page (e.g. when visiting on iOS Safari), the user inadvertently was redirected to the Firefox Private Network (FPN) website.

![image](https://user-images.githubusercontent.com/17312341/96692723-9468cc80-13b0-11eb-8408-c026dd85a63c.png)

This is likely because the entire Test Pilot website has been redirected to FPN. (Original Link URL: https://testpilot.firefox.com/experiments/color).

**Comment by Rob--W** [comment]
Thanks @reinhart1010 for reporting this issue. I am going to fix that in #959 .
