### ISSUE TITLE
Add using storage.sync for saved themes?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/FirefoxColor#96]
I just remembered that [`storage.sync`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync) is a thing. But, it's only a thing for the add-on. That could make it of limited use, though possibly a handy enhancement.

**Comment by nt1m** [comment]
Some people don't want their theme to synchronise across devices.

**Comment by lmorchard** [comment]
> Some people don't want their theme to synchronise across devices.

That's a good point. This would have to be optional. Though, to be clear, what I mean is that this would be synching the set of saved theme options in the web editor - not necessarily synching the actual current theme applied to the browser.
