### ISSUE TITLE
Unable to change the sidebar's border colour

### ISSUE THREAD

**Issue by Peilonrayz** [mozilla/FirefoxColor#960]
Firefox Color doesn't change the colour of the border which you use to resize the sidebar. This is causing my theme to have an annoying discolouring that stands out.

![firefox](https://user-images.githubusercontent.com/5623093/101539441-740fc400-3996-11eb-8fad-41787b10c781.png)

I'm unsure if this is a problem with Firefox, not Firefox Color, as the sidebar's search box is also similarly discoloured. Getting the values from GTK.

**Comment by Rob--W** [comment]
I don't see anything super obviously wrong in your screenshot, so I'll need a bit more information.
Could you provide more details?

1. Link to the theme.
2. An explanation of what you're expecting, and what happens instead.

**Comment by Peilonrayz** [comment]
1.  Sure, here is a [link](https://color.firefox.com/?theme=XQAAAAJlBAAAAAAAAABBKYhm849SCicxcUhA3DJozHnOMuotJJDHi8ajvY2nrbwtWf53IW6FuNS6kABmHjQtYV0LyoDuxGGbkPNrE1DlVUWcgNiQMycZIeefh-FT7iUiTx8i8fwxQF9iTG6KYplTBFfm-7A_NHKF_sZ9Vjv7pOYGlqfDHJpXBBcorB91Gh7s_6mQoueRBvxyUanSDm7jM8iNcFtiiLEFX9Rvcy80JFXxHnYzqbs0JktGEWKHcmTT1e9pNa3xqg_AwnjOh1wSDjASx4hT2wLmaGpeg-FAJpfWmqReNZEXw50YNu1G2ViHPcs5kjc0pPTZsVumt6tHT_xsZ1UnrEb1QL7Rv4_ONOFICQEaHapvZ3_vdYdcYgHy79_ioSatNLlrM2C9o2Du5AhOJB33-TMf2uPAULEcV3JMtPBr00S6K-SX2ALwz-i9eiTNKAuz3_XVK9IC4Hfx_5oBNgsYDOPynP3CavLNEYL284FeWczHF6llkZzvwzDeCEZUex8f1Bm0zy2GvvwWEBE). I have only used 5 colours and none of them are the blue showing up in my screen shot.
2.  I'm not sure how to better describe it. The border between the History sidebar and the main view, displaying Firefox Color, is blue. I have not used blue anywhere in my theme. I want to be able to change it to something like the following, grey. (Made through an image editor)

    ![firefox](https://user-images.githubusercontent.com/5623093/101644120-bbe12a80-3a2c-11eb-8a2d-03d32ffa271d.png)

    The search bar in the History sidebar is also the same blues but I don't really mind as I don't use that sidebar view often.

**Comment by Rob--W** [comment]
I see, but only after zooming in and putting the images next to each other.

Are you using Linux? I used the browser toolbox to inspect that bar, its class name is "sidebar-splitter", which is transparent on most platforms, except on Linux:
- All platforms: `background-color: transparent;` @ https://searchfox.org/mozilla-central/rev/ffdb6a4d934b3f5294f18cf0e1df618109ccb36b/browser/themes/shared/sidebar.inc.css#24,32
- Linux: `background-color: -moz-dialog;` @ https://searchfox.org/mozilla-central/rev/ffdb6a4d934b3f5294f18cf0e1df618109ccb36b/browser/themes/linux/browser.css#302

It's not possible to customize the sidebar bar through the extension theme API, but that color can be customized by setting the `ui.-moz-dialog` preference to the desired color string. It will affect anything else that uses the `-moz-dialog` color value though.

Is this an acceptable work-around to you?

**Comment by Peilonrayz** [comment]
Sorry I couldn't have been more clear. Yes, I'm using Linux. I've got that to work by fiddling with my `userChrome.css`. Thank you Rob--W you've been a great help.

`chrome/userChrome.css`
```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

.sidebar-splitter {
  border-color: #111111 !important;
  background-color: #111111 !important;
}
```

This seems like it's not an issue with Firefox Colour so I'll close the issue. Again thank you Rob--W.
