### ISSUE TITLE
While scrolling bug arises

### ISSUE THREAD

**Issue by himanshujaidka** [mozilla/FirefoxColor#961]
https://user-images.githubusercontent.com/58654018/103333791-1f430300-4a95-11eb-9fe8-11bec560b05e.mp4

While working on issue no 883 I found that while scrolling there is a bug arise with .theme-colors-editor__picker

**Comment by Rob--W** [comment]
I watched the video a couple of times, but can't see anything wrong with it. Could you explain what you believe to be wrong?

**Comment by himanshujaidka** [comment]
sir, open this web extension, then go to advanced color and select any of its options, then after selection, scroll down the screen then you will see that after scrolling the option will disappear and according to me it will not disappear while the user scrolling down the screen.

**Comment by himanshujaidka** [comment]
![Screenshot (119)_LI](https://user-images.githubusercontent.com/58654018/103551506-70595980-4ed0-11eb-9756-4e98b7d2a3b6.jpg)
Before scrolling

**Comment by himanshujaidka** [comment]
![Uploading Screenshot (120)_LI.jpg…]()
after scrolling

**Comment by himanshujaidka** [comment]
![Screenshot (120)_LI](https://user-images.githubusercontent.com/58654018/103551604-9121af00-4ed0-11eb-9996-92de778fac98.jpg)
after scrolling

**Comment by Rob--W** [comment]
This doesn't happen due to scrolling, but due to unfocusing the selected color.

This is working as intended.

**Comment by himanshujaidka** [comment]
okay

**Comment by himanshujaidka** [comment]
![Screenshot (121)](https://user-images.githubusercontent.com/58654018/103555376-2bd0bc80-4ed6-11eb-9c56-17f210a16cd1.png)
 if the user want to scroll down to see more options or to see anything else then after scrolling or while touching the scrollbar the whole panel will disappear

**Comment by himanshujaidka** [comment]
https://user-images.githubusercontent.com/58654018/103567668-37c67980-4eea-11eb-8d07-5a82ffa1f3c5.mp4

and @Rob--W one more thing sir, when user small the tab size then after scrolling it will look like this and user unable to create their fav theme
