### ISSUE TITLE
Firefox didn't get notify of switch  theme on linux OS

### ISSUE THREAD

**Issue by spphinslove** [mozilla/FirefoxColor#967]
![图片](https://user-images.githubusercontent.com/11383988/109424392-65c5c700-7a1e-11eb-8c71-2ec3d640212f.png)
![图片](https://user-images.githubusercontent.com/11383988/109424427-89890d00-7a1e-11eb-9eee-c0ee831047ef.png)
**other application (GTK3) can switch normally**
I must restart firefox so it can switch to dark or light theme

PS:I have installed Dark Reader plugin for firefox,and set it follow the firefox theme color.I also set firefox theme follow the OS theme color.

**Comment by Rob--W** [comment]
When Firefox Color is in use, one theme is used for the browser interface regardless of your OS theme preference.

Similarly, when the Dark Reader plugin is used, all content pages are dark.

What would you expect after changing the OS themes, given that both of your theme/color choices have been fixed to a dark theme?

**Comment by spphinslove** [comment]
> When Firefox Color is in use, one theme is used for the browser interface regardless of your OS theme preference.
> 
> Similarly, when the Dark Reader plugin is used, all content pages are dark.
> 
> What would you expect after changing the OS themes, given that both of your theme/color choices have been fixed to a dark theme?

if you switch theme between dark and light on Windows10,firefox default theme color will follow the OS theme color soon.but on linux I cant do that.

**Comment by Rob--W** [comment]
> Firefox default theme color

I think that you're not referring to the Firefox Color add-on, but to the default theme of Firefox (literally the default theme). This issue tracker is about the Firefox Color add-on, not about Firefox's built-in themes.

Use https://bugzilla.mozilla.org/ for Firefox bugs, specifically Firefox product + Themes component for bugs about themes. Here is a list of open bugs for themes: https://bugzilla.mozilla.org/buglist.cgi?product=Firefox&component=Theme&bug_status=__open__

Note: There are two relevant parts for the "dark theme" experience:
- Content "themes" (color schemes), is supposed to reflect the system's preference for the (dark) theme. If it does not have the desired value, visit `about:config` and edit/create `ui.systemUsesDarkTheme` . Supported values are 0 (light theme, default) and 1 (dark theme).
- Browser UI theme, visit `about:addons`, Themes section and choose Dark of Light if the default value doesn't cut it.
