### ISSUE TITLE
Greenkeeper.io has been shutdown

### ISSUE THREAD

**Issue by Standard8** [mozilla/FirefoxColor#968]
We're opening this issue because your project has previously used [Greenkeeper.io](https://greenkeeper.io/). Greenkeeper.io was shutdown on 3rd June 2020. We are therefore removing the obsolete Greenkeeper.io integration.

If you are already using an alternative solution, you can close and ignore this issue.

Other alternatives are available, various Mozilla repositories already use Renovate.

If you have any questions, reach out in #github-admin:mozilla.org on matrix.

**Comment by Rob--W** [comment]
Already handled in https://github.com/mozilla/FirefoxColor/commit/df4ff6c1c057ac34737bad5e47b6c5a83712893d
