### ISSUE TITLE
Cannot export theme, extension does not work

### ISSUE THREAD

**Issue by seanpm2001** [mozilla/FirefoxColor#971]
***

# Cannot export theme

This has been a common issue I have noted by looking at reviews from the past 7 months. I went to install this extension today, and I found that every time I exported the file, it said that it couldn't install the extension, as the extension was corrupt. I can confirm it is, as there is a <600 byte blank SVG file, and a normal JSON file. I am surprised that this isn't being reported as much as it should. I looked through issues before reporting, but couldn't find any recent ones mentioning this, so I will say it here. This may be a duplicate, as this apparently has been an issue for 7 months or more.

I tried to include a screenshot, but the error message goes away before my system can get a screenshot (using F10: PRT SC/Print Screen)

## Device specs

Browser version: Firefox Browser 87.0 for Ubuntu Linux 20.04.1
Operating system: Ubuntu Linux 20.04.1
DE: GNOME 3.36.1

***

**Comment by caitmuenster** [comment]
Thanks for filing, @seampm2001. We should have better documentation for this. If you export the theme, you'll need to sign it on addons.mozilla.org in order to install it successfully. Here are some quick steps: 

1. Sign in to addons.mozilla.org 
2. Click "Submit a New Theme" 
3. On the screen that asks "How to Distribute This Version," select "on this site" if you want the theme to be publicly available on addons.mozilla.org, or "on your own" if you only want to make it available to people you share the file with 
4. On the "Upload Version" screen, click "Select a file..." and then select your exported file. (It should be a .zip or an .xpi). Check the box for the "Firefox" application. Once the file has been validated, click Continue. 
5. If you have selected "distribute on addons.mozilla.org," fill out the page for the requested information to describe the add-on. 
6. You're done! Once your theme is approved by a reviewer, you will get an email with a link to download the signed file from. You can install the signed file.

**Comment by caitmuenster** [comment]
Oh, sorry @seanpm2001, I did not read your issue closely enough! 😅

Can you check your computer system's timestamp? Usually add-ons fail to install because the system clock is out of sync. If that's not the case, we can investigate some other culprits.

**Comment by Rob--W** [comment]
> I went to install this extension today, and I found that every time I exported the file, it said that it couldn't install the extension, as the extension was corrupt. I can confirm it is, as there is a <600 byte blank SVG file, and a normal JSON file

It does really sound like the theme package wasn't signed. Add-ons can only be installed once signed. Caitlin's instructions above should help with that.

@seanpm2001 Could you clarify: Are you asking about the inability to export the theme, or the inability to install / import it again?

FYI: It's a currently known limitation that SVG files cannot be loaded via Firefox Color. If there is evidence that this is a significant issue, then we can consider bumping the priority of https://bugzilla.mozilla.org/show_bug.cgi?id=1491790

**Comment by seanpm2001** [comment]
@Rob--W The theme zip file contains a blank SVG file, i assume these are the theme graphics. To clarify, I have an inability to export the theme. I have tested the extension in multiple Firefox profiles, and I have the same issue. The theme comes up as corrupt when I try to load it.

@caitmuenster I can't get a timestamp for this, as I don't know how to get a time stamp for Firefox. It installed correctly, as everything in the extension works except for the export function. I have noted that some of the top critical reviews on [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/firefox-color/reviews/?score=1) mention the same exact issue, and I am encountering it as well. I decided to open it here, as no-one else seems to have yet. I want to make sure this extension works for everyone who needs it.

**Comment by seanpm2001** [comment]
Can we have a pinned notice on this repository to let people know the correct process, or add the process in the README so other people know what to do. I haven't tested the signing method yet, as I don't know where to sign the file.

**Comment by Rob--W** [comment]
> @Rob--W The theme zip file contains a blank SVG file, i assume these are the theme graphics. To clarify, I have an inability to export the theme. I have tested the extension in multiple Firefox profiles, and I have the same issue. The theme comes up as corrupt when I try to load it.

If you have a zip file, then the export has succeeded.

To test temporarily, visit about: debugging and load the file. Does that work temporarily?

 To get it signed, see https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/
Note that Caitlin has already explained how to do so in a previous comment (the first one).

**Comment by caitmuenster** [comment]
> Can we have a pinned notice on this repository to let people know the correct process, or add the process in the README so other people know what to do.

Absolutely. I might not be able to get to it this week, but it's on my list. :)

**Comment by seanpm2001** [comment]
A little bit late, but I went to about:debugging and was able to temporarily load the theme. It is functional, we just need documentation to let people know to do this, or give off some other warning instead of just saying the theme is corrupt.

**Comment by Rob--W** [comment]
I have opened some pull requests to make it easier to understand how the package can be used by those unfamiliar with extension development.
